//! Bytecode to Rust: each chunk becomes a function whose registers are
//! locals and whose basic blocks are the arms of a block machine.

use std::collections::BTreeSet;
use std::fmt::Write;

use crate::module::{Chunk, Code, Module};
use crate::op::Op;
use crate::value::Value;
use crate::vm::native_code::build_hash;

/// The Rust module running `module`'s systems: one function per chunk they
/// reach, and a `NATIVE` table of them for
/// [`Vm::install_native`](crate::Vm::install_native). `krate` is the path the
/// generated code names this crate by (`viso_behavior`, or a re-export).
///
/// The output is deterministic: the same module lowers to the same text.
pub fn lower_systems(module: &Module, krate: &str) -> String {
    let chunks = reachable(module);
    let mut out = String::new();
    let build = build_hash(module);
    let _ = write!(
        out,
        "//! Generated by `lower_systems` from build {build:#018x}: the systems'\n\
         //! chunks compiled to Rust. Do not edit; regenerate from the module.\n\n\
         #![allow(unused_mut, unused_variables, unused_assignments, unused_imports)]\n\
         #![allow(unreachable_code, unreachable_patterns, non_snake_case)]\n\
         #![allow(clippy::all, clippy::pedantic, clippy::nursery)]\n\n\
         use {krate}::aot::{{self as rt, NativeCode, PathStep}};\n\
         use {krate}::{{Arith, ArithOp, DisplayKind, FaultKind, Instance, Num, Value, Vm}};\n\n\
         macro_rules! t {{\n    ($vm:ident, $c:expr, $pc:expr, $e:expr) => {{\n        \
         match $e {{\n            Ok(v) => v,\n            Err(k) => return Err(rt::at($vm, $c, $pc, k)),\n        \
         }}\n    }};\n}}\n\n\
         /// The compiled chunks, for `Vm::install_native`.\n\
         pub static NATIVE: NativeCode = NativeCode {{\n    build: {build:#018x},\n    chunks: &[\n"
    );
    let compiled: Vec<u32> = chunks
        .iter()
        .copied()
        .filter(|&c| module.chunk(c).body.is_ok())
        .collect();
    for c in &compiled {
        let _ = writeln!(out, "        ({c}, s{c}),");
    }
    out.push_str("    ],\n};\n");
    for &c in &compiled {
        let chunk = module.chunk(c);
        if let Ok(code) = &chunk.body {
            lower_chunk(&mut out, module, c, chunk, code);
        }
    }
    out
}

/// The chunks the systems run, ascending: their hooks and state
/// initializers, and every chunk those call or close over.
fn reachable(module: &Module) -> BTreeSet<u32> {
    let mut seen = BTreeSet::new();
    let mut stack: Vec<u32> = Vec::new();
    for system in module.systems() {
        stack.extend(system.hooks.iter().map(|&(_, chunk)| chunk));
        let layout = module.layout(system.component);
        stack.extend(layout.state_inits.iter().flatten().copied());
        stack.extend(layout.input_defaults.iter().flatten().copied());
    }
    while let Some(c) = stack.pop() {
        if !seen.insert(c) {
            continue;
        }
        let Ok(code) = &module.chunk(c).body else {
            continue;
        };
        for op in code.ops.iter() {
            match *op {
                Op::Call { ext, .. } | Op::Closure { ext, .. } | Op::Start { ext } => {
                    stack.push(code.ext[ext as usize]);
                }
                _ => {}
            }
        }
    }
    seen
}

/// Whether control does not fall through `op` to the next.
fn ends_block(op: &Op) -> bool {
    matches!(
        op,
        Op::Jump { .. }
            | Op::JumpIf { .. }
            | Op::JumpUnless { .. }
            | Op::Switch { .. }
            | Op::Return { .. }
            | Op::Unreachable
    )
}

/// The first op of every basic block of `code`, ascending.
fn leaders(code: &Code) -> BTreeSet<usize> {
    let mut leaders = BTreeSet::from([0]);
    for (i, op) in code.ops.iter().enumerate() {
        match *op {
            Op::Jump { target } => {
                leaders.insert(target as usize);
            }
            Op::JumpIf { target, .. } | Op::JumpUnless { target, .. } => {
                leaders.insert(target as usize);
            }
            Op::Switch { ext, .. } => {
                let at = ext as usize;
                leaders.insert(code.ext[at + 2] as usize);
                let n = code.ext[at + 3] as usize;
                leaders.extend(code.ext[at + 4..at + 4 + n].iter().map(|&t| t as usize));
            }
            _ => {}
        }
        if ends_block(op) {
            leaders.insert(i + 1);
        }
    }
    leaders.retain(|&l| l < code.ops.len());
    leaders
}

/// `rN`.
fn r(n: impl Into<u32>) -> String {
    format!("r{}", n.into())
}

/// The clones of the registers `regs`, comma-separated.
fn clones(regs: &[u32]) -> String {
    regs.iter()
        .map(|&x| format!("{}.clone()", r(x)))
        .collect::<Vec<_>>()
        .join(", ")
}

/// A Rust expression of the scalar constant `value`, if it is one.
fn literal(value: &Value) -> Option<String> {
    Some(match value {
        Value::Nil => "Value::Nil".to_owned(),
        Value::Int(i64::MIN) => "Value::Int(i64::MIN)".to_owned(),
        Value::Int(n) => format!("Value::Int({n})"),
        Value::Float(x) => format!("Value::Float(f64::from_bits({:#x}))", x.to_bits()),
        _ => return None,
    })
}

fn lower_chunk(out: &mut String, module: &Module, c: u32, chunk: &Chunk, code: &Code) {
    let params = u32::from(chunk.params);
    let captures: Vec<u32> = chunk.captures.iter().map(|&x| u32::from(x)).collect();
    let mut signature: Vec<String> = (0..params)
        .map(|p| format!("mut {}: Value", r(p)))
        .collect();
    signature.extend(captures.iter().map(|&x| format!("mut {}: Value", r(x))));
    let _ = write!(
        out,
        "\n/// {:?} (chunk {c}).\nfn c{c}(vm: &mut Vm, inst: &mut Instance, depth: usize{}{}) -> Result<Value, FaultKind> {{\n",
        &*chunk.name,
        if signature.is_empty() { "" } else { ", " },
        signature.join(", ")
    );
    for x in 0..u32::from(chunk.regs) {
        if x >= params && !captures.contains(&x) {
            let _ = writeln!(out, "    let mut {} = Value::Nil;", r(x));
        }
    }
    let pooled = code.ops.iter().any(|op| match *op {
        Op::Const { index, .. } => literal(&code.consts[index as usize]).is_none(),
        _ => false,
    });
    if pooled {
        let _ = writeln!(
            out,
            "    let module = rt::module(vm);\n    let k = rt::consts(&module, {c});"
        );
    }
    out.push_str("    let mut pc: u32 = 0;\n    loop {\n        match pc {\n");
    let leaders = leaders(code);
    let starts: Vec<usize> = leaders.iter().copied().collect();
    for (b, &start) in starts.iter().enumerate() {
        let end = starts.get(b + 1).copied().unwrap_or(code.ops.len());
        let _ = writeln!(out, "            {start} => {{");
        for i in start..end {
            lower_op(out, module, c, code, i);
        }
        if !ends_block(&code.ops[end - 1]) {
            let _ = writeln!(
                out,
                "                pc = {end};\n                continue;"
            );
        }
        out.push_str("            }\n");
    }
    let _ = writeln!(
        out,
        "            _ => return Err(rt::at(vm, {c}, 0, FaultKind::Internal)),\n        }}\n    }}\n}}"
    );
    // The uniform entry the table holds.
    let mut args: Vec<String> = (0..params).map(|p| format!("args[{p}].clone()")).collect();
    args.extend((0..captures.len()).map(|i| format!("caps[{i}].clone()")));
    let _ = writeln!(
        out,
        "\nfn s{c}(vm: &mut Vm, inst: &mut Instance, depth: usize, args: &[Value], caps: &[Value]) -> Result<Value, FaultKind> {{\n    c{c}(vm, inst, depth{}{})\n}}",
        if args.is_empty() { "" } else { ", " },
        args.join(", ")
    );
}

fn lower_op(out: &mut String, module: &Module, c: u32, code: &Code, i: usize) {
    let op = code.ops[i];
    let ext = |at: u32| &code.ext[at as usize..];
    // A fault of the op itself, with the interpreter's cursor past it.
    let t = |e: &str| format!("t!(vm, {c}, {}, {e})", i + 1);
    let mut line = |s: String| {
        let _ = writeln!(out, "                {s}");
    };
    line(format!("t!(vm, {c}, {i}, rt::tick(vm));"));
    match op {
        Op::Const { dst, index } => {
            let value = &code.consts[index as usize];
            let expr = literal(value).unwrap_or_else(|| format!("k[{index}].clone()"));
            line(format!("{} = {expr};", r(dst)));
        }
        Op::Int { dst, value } => line(format!("{} = Value::Int({value});", r(dst))),
        Op::Nil { dst } => line(format!("{} = Value::Nil;", r(dst))),
        Op::Move { dst, src } => {
            if dst != src {
                line(format!("{} = {}.clone();", r(dst), r(src)));
            }
        }
        Op::LoadState { dst, slot } => {
            line(format!(
                "{} = {};",
                r(dst),
                t(&format!("rt::load_state(inst, {slot})"))
            ));
        }
        Op::StoreState { src, slot } => line(format!(
            "{};",
            t(&format!(
                "rt::store_state(vm, inst, {slot}, {}.clone())",
                r(src)
            ))
        )),
        Op::LoadInput { dst, slot } => {
            line(format!(
                "{} = {};",
                r(dst),
                t(&format!("rt::load_input(inst, {slot})"))
            ));
        }
        Op::AddI64 { dst, a, b } | Op::SubI64 { dst, a, b } | Op::MulI64 { dst, a, b } => {
            let method = match op {
                Op::AddI64 { .. } => "checked_add",
                Op::SubI64 { .. } => "checked_sub",
                _ => "checked_mul",
            };
            line(format!(
                "{} = Value::Int({});",
                r(dst),
                t(&format!(
                    "{}.{method}({}).ok_or(FaultKind::Overflow)",
                    t(&format!("rt::int(&{})", r(a))),
                    t(&format!("rt::int(&{})", r(b)))
                ))
            ));
        }
        Op::LtI64 { dst, a, b } | Op::LeI64 { dst, a, b } => {
            let cmp = if matches!(op, Op::LtI64 { .. }) {
                "<"
            } else {
                "<="
            };
            line(format!(
                "{} = Value::bool({} {cmp} {});",
                r(dst),
                t(&format!("rt::int(&{})", r(a))),
                t(&format!("rt::int(&{})", r(b)))
            ));
        }
        Op::AddF64 { dst, a, b }
        | Op::SubF64 { dst, a, b }
        | Op::MulF64 { dst, a, b }
        | Op::DivF64 { dst, a, b } => {
            let sym = match op {
                Op::AddF64 { .. } => "+",
                Op::SubF64 { .. } => "-",
                Op::MulF64 { .. } => "*",
                _ => "/",
            };
            line(format!(
                "{} = Value::Float({} {sym} {});",
                r(dst),
                t(&format!("rt::float(&{})", r(a))),
                t(&format!("rt::float(&{})", r(b)))
            ));
        }
        Op::LtF64 { dst, a, b } | Op::LeF64 { dst, a, b } => {
            let cmp = if matches!(op, Op::LtF64 { .. }) {
                "<"
            } else {
                "<="
            };
            line(format!(
                "{} = Value::bool({} {cmp} {});",
                r(dst),
                t(&format!("rt::float(&{})", r(a))),
                t(&format!("rt::float(&{})", r(b)))
            ));
        }
        Op::Arith { op, dst, a, b } => line(format!(
            "{} = {};",
            r(dst),
            t(&format!(
                "rt::arith(ArithOp::new(Arith::{:?}, Num::{:?}), &{}, &{})",
                op.op(),
                op.num(),
                r(a),
                r(b)
            ))
        )),
        Op::Eq { dst, a, b } => line(format!("{} = Value::bool({} == {});", r(dst), r(a), r(b))),
        Op::Ne { dst, a, b } => line(format!("{} = Value::bool({} != {});", r(dst), r(a), r(b))),
        Op::Neg { num, dst, src } => line(format!(
            "{} = {};",
            r(dst),
            t(&format!("rt::neg(Num::{num:?}, &{})", r(src)))
        )),
        Op::Not { dst, src } => line(format!(
            "{} = Value::bool({} == 0);",
            r(dst),
            t(&format!("rt::int(&{})", r(src)))
        )),
        Op::BitNot { num, dst, src } => line(format!(
            "{} = {};",
            r(dst),
            t(&format!("rt::bit_not(Num::{num:?}, &{})", r(src)))
        )),
        Op::Cast { from, to, dst, src } => line(format!(
            "{} = {};",
            r(dst),
            t(&format!(
                "rt::cast(Num::{from:?}, Num::{to:?}, &{})",
                r(src)
            ))
        )),
        Op::Call { dst, ext: at } => {
            let e = ext(at);
            let (func, argc) = (e[0], e[1] as usize);
            let args = &e[2..2 + argc];
            let callee = module.chunk(func);
            line(format!(
                "{} = match {} {{",
                r(dst),
                t(&format!("rt::memo_enter(vm, inst, {func})"))
            ));
            line("    Some(v) => v,".to_owned());
            if callee.body.is_ok() {
                let mut call: Vec<String> =
                    args.iter().map(|&x| format!("{}.clone()", r(x))).collect();
                call.extend(callee.captures.iter().map(|_| "Value::Nil".to_owned()));
                line(format!(
                    "    None => {{ {}; c{func}(vm, inst, depth + 1{}{})? }}",
                    t("rt::depth(vm, depth)"),
                    if call.is_empty() { "" } else { ", " },
                    call.join(", ")
                ));
            } else {
                line(format!(
                    "    None => {{ let k = rt::unsupported(vm, {func}); return Err(rt::at(vm, {c}, {}, k)); }}",
                    i + 1
                ));
            }
            line("};".to_owned());
        }
        Op::CallValue { dst, ext: at } => {
            let e = ext(at);
            let argc = e[1] as usize;
            line(format!(
                "{} = {};",
                r(dst),
                t(&format!(
                    "rt::call_value(vm, inst, depth, &{}, &[{}])",
                    r(e[0]),
                    clones(&e[2..2 + argc])
                ))
            ));
        }
        Op::Native { dst, ext: at } => {
            let e = ext(at);
            let argc = e[1] as usize;
            let mut s = String::from("{ let mut a = rt::scratch(vm); ");
            for &x in &e[2..2 + argc] {
                let _ = write!(s, "a.push({}.clone()); ", r(x));
            }
            let _ = write!(
                s,
                "{} = {}; }}",
                r(dst),
                t(&format!("rt::native(vm, {}, a)", e[0]))
            );
            line(s);
        }
        Op::Closure { dst, ext: at } => {
            let e = ext(at);
            let n = e[1] as usize;
            line(format!(
                "{} = {};",
                r(dst),
                t(&format!(
                    "rt::closure(vm, {}, Box::from([{}]))",
                    e[0],
                    clones(&e[2..2 + n])
                ))
            ));
        }
        Op::Make { dst, ext: at } => {
            let e = ext(at);
            let n = e[1] as usize;
            line(format!(
                "{} = {};",
                r(dst),
                t(&format!(
                    "rt::make(vm, {}, Box::from([{}]))",
                    e[0],
                    clones(&e[2..2 + n])
                ))
            ));
        }
        Op::List { dst, ext: at } => {
            let e = ext(at);
            let n = e[0] as usize;
            line(format!(
                "{} = {};",
                r(dst),
                t(&format!("rt::list(vm, vec![{}])", clones(&e[1..1 + n])))
            ));
        }
        Op::Concat { dst, ext: at } => {
            let e = ext(at);
            let n = e[0] as usize;
            let parts: Vec<String> = e[1..1 + n].iter().map(|&x| format!("&{}", r(x))).collect();
            line(format!(
                "{} = {};",
                r(dst),
                t(&format!("rt::concat(vm, &[{}])", parts.join(", ")))
            ));
        }
        Op::Translate { dst, ext: at } => {
            let e = ext(at);
            let n = e[2] as usize;
            let mut s = String::from("{ let mut a = rt::scratch(vm); ");
            for &x in &e[3..3 + n] {
                let _ = write!(s, "a.push({}.clone()); ", r(x));
            }
            let _ = write!(
                s,
                "{} = {}; }}",
                r(dst),
                t(&format!("rt::translate(vm, &{}, &{}, a)", r(e[0]), r(e[1])))
            );
            line(s);
        }
        Op::Field { dst, src, index } => line(format!(
            "{} = {};",
            r(dst),
            t(&format!("rt::field(&{}, {index})", r(src)))
        )),
        Op::Index { dst, list, index } => line(format!(
            "{} = {};",
            r(dst),
            t(&format!("rt::index(vm, &{}, &{})", r(list), r(index)))
        )),
        Op::SetPath { root, ext: at } => {
            let e = ext(at);
            let n = e[1] as usize;
            let steps: Vec<String> = e[2..2 + 2 * n]
                .chunks(2)
                .map(|step| match step[0] {
                    0 => format!("PathStep::Field({})", step[1]),
                    // The interpreter has taken the root out of its register.
                    _ if step[1] == u32::from(root) => "PathStep::Index(&Value::Nil)".to_owned(),
                    _ => format!("PathStep::Index(&{})", r(step[1])),
                })
                .collect();
            line(format!(
                "{{ let src = {}.clone(); {}; }}",
                r(e[0]),
                t(&format!(
                    "rt::set_path(vm, &mut {}, &[{}], src)",
                    r(root),
                    steps.join(", ")
                ))
            ));
        }
        Op::Push { list, item } => line(format!(
            "{{ let item = {}.clone(); {}; }}",
            r(item),
            t(&format!("rt::push(vm, &mut {}, item)", r(list)))
        )),
        Op::Insert { list, index, item } => line(format!(
            "{{ let index = {}.clone(); let item = {}.clone(); {}; }}",
            r(index),
            r(item),
            t(&format!("rt::insert(vm, &mut {}, &index, item)", r(list)))
        )),
        Op::Remove { dst, list, index } => line(format!(
            "{{ let index = {}.clone(); {} = {}; }}",
            r(index),
            r(dst),
            t(&format!("rt::remove(vm, &mut {}, &index)", r(list)))
        )),
        Op::Truncate { list, len } => line(format!(
            "{{ let len = {}.clone(); {}; }}",
            r(len),
            t(&format!("rt::truncate(vm, &mut {}, &len)", r(list)))
        )),
        Op::Len { dst, src } => line(format!(
            "{} = {};",
            r(dst),
            t(&format!("rt::len(&{})", r(src)))
        )),
        Op::Tag { dst, src } => line(format!(
            "{} = {};",
            r(dst),
            t(&format!("rt::tag(&{})", r(src)))
        )),
        Op::IsNil { dst, src } => line(format!("{} = Value::bool({}.is_nil());", r(dst), r(src))),
        Op::Jump { target } => line(format!("pc = {target};\n                continue;")),
        Op::JumpIf { cond, target } | Op::JumpUnless { cond, target } => {
            let cmp = if matches!(op, Op::JumpIf { .. }) {
                "!="
            } else {
                "=="
            };
            line(format!(
                "pc = if {} {cmp} 0 {{ {target} }} else {{ {} }};\n                continue;",
                t(&format!("rt::int(&{})", r(cond))),
                i + 1
            ));
        }
        Op::Switch { src, ext: at } => {
            let e = ext(at);
            let first = ((u64::from(e[1]) << 32) | u64::from(e[0])) as i64;
            let (default, n) = (e[2], e[3] as usize);
            let mut s = format!(
                "pc = match {}.checked_sub({}) {{ ",
                t(&format!("rt::int(&{})", r(src))),
                if first == i64::MIN {
                    "i64::MIN".to_owned()
                } else {
                    format!("{first}")
                }
            );
            for (k, &target) in e[4..4 + n].iter().enumerate() {
                let _ = write!(s, "Some({k}) => {target}, ");
            }
            let _ = write!(s, "_ => {default} }};\n                continue;");
            line(s);
        }
        Op::Return { src } => line(format!(
            "return Ok(rt::ret(vm, inst, {c}, std::mem::take(&mut {})));",
            r(src)
        )),
        Op::Emit { ext: at } => {
            let e = ext(at);
            let n = e[1] as usize;
            line(format!(
                "{};",
                t(&format!(
                    "rt::emit(vm, {}, Box::from([{}]))",
                    e[0],
                    clones(&e[2..2 + n])
                ))
            ));
        }
        Op::Start { ext: at } => {
            let e = ext(at);
            let argc = e[1] as usize;
            let tail = &e[2 + argc..7 + argc];
            let handler = |x: u32| {
                if x == u32::MAX {
                    "None".to_owned()
                } else {
                    format!("Some({}.clone())", r(x))
                }
            };
            line(format!(
                "{};",
                t(&format!(
                    "rt::start(vm, {}, Box::from([{}]), {}, {}, {}, {}, {})",
                    e[0],
                    clones(&e[2..2 + argc]),
                    handler(tail[0]),
                    handler(tail[1]),
                    tail[2],
                    tail[3],
                    tail[4]
                ))
            ));
        }
        Op::Display { kind, dst, src } => line(format!(
            "{} = {};",
            r(dst),
            t(&format!(
                "rt::display(vm, DisplayKind::{kind:?}, &{})",
                r(src)
            ))
        )),
        Op::DisplayDim { dst, src, suffix } => {
            let suffix = code.consts[usize::from(suffix)]
                .as_str()
                .unwrap_or_default();
            line(format!(
                "{} = {};",
                r(dst),
                t(&format!("rt::display_dim(vm, &{}, {suffix:?})", r(src)))
            ));
        }
        Op::Unreachable => line(format!(
            "{{ let k = rt::unreachable(vm); return Err(rt::at(vm, {c}, {}, k)); }}",
            i + 1
        )),
    }
}
