//! `#[derive(GpuInstance)]` — emit an explicit, validated instance layout.
//!
//! For a `#[repr(C)]` struct of GPU scalar/vector fields, the derive generates:
//!
//! 1. `unsafe impl viso_gpu::GpuInstance` with `const STRIDE = size_of::<Self>()`.
//! 2. An inherent `const LAYOUT: viso_gpu::InstanceLayout` describing every
//!    field as `{ name, offset, format }`, where `offset` comes from
//!    `core::mem::offset_of!` — the *real* `#[repr(C)]` offset, not a guess.
//! 3. An inherent `fn validate_against(schema) -> Result<(), LayoutError>`
//!    forwarding to `LAYOUT.validate_against(schema)`.
//!
//! This is the explicit replacement for makepad's `DrawVars` trailing-memory
//! `from_raw_parts` trick (`draw_vars.rs:192`): rather than reinterpreting "all
//! bytes after field X" as instance data, we name each field and record its
//! offset, then cross-check against the shader's declared schema at pipeline
//! registration (§32). Modeled on makepad's `DrawShaderInputs`
//! (`platform/src/draw_shader.rs`), but keyed on byte offsets since our instance
//! struct *is* the `#[repr(C)]` layout.
//!
//! Field types are restricted to 4-byte-aligned GPU scalars/vectors:
//! `f32`, `[f32; 2|3|4]`, `u32`, `[u32; 2|4]`. Anything else is a compile error
//! at the field, so the generated `offset_of!` never straddles padding the GPU
//! can't describe.

use proc_macro2::TokenStream;
use quote::{quote, quote_spanned};
use syn::spanned::Spanned;
use syn::{Data, DeriveInput, Fields, Type};

/// Entry point for the derive; see the module docs.
pub fn derive(input: DeriveInput) -> TokenStream {
    let name = &input.ident;
    let (impl_generics, ty_generics, where_clause) = input.generics.split_for_impl();

    // 1. Must be a struct with named fields.
    let fields = match &input.data {
        Data::Struct(s) => match &s.fields {
            Fields::Named(named) => &named.named,
            _ => {
                return err(
                    input.span(),
                    "GpuInstance requires a struct with named fields",
                );
            }
        },
        _ => return err(input.span(), "GpuInstance can only be derived for structs"),
    };

    // 2. Must be `#[repr(C)]` — the whole point is a stable, declarable layout.
    if !has_repr_c(&input) {
        return err(
            input.span(),
            "GpuInstance requires `#[repr(C)]` for a stable GPU layout",
        );
    }

    // 3. Build one InstanceField initializer per field, mapping the field type
    //    to an AttrFormat and taking its real offset via `offset_of!`.
    let mut field_inits = Vec::with_capacity(fields.len());
    for field in fields {
        let ident = field.ident.as_ref().expect("named field");
        let fname = ident.to_string();
        let Some(fmt) = attr_format(&field.ty) else {
            return err(
                field.ty.span(),
                "unsupported GpuInstance field type: expected `f32`, `[f32; 2|3|4]`, \
                 `u32`, or `[u32; 2|4]`",
            );
        };
        field_inits.push(quote_spanned! {field.span()=>
            ::viso_gpu::InstanceField {
                name: #fname,
                offset: ::core::mem::offset_of!(#name, #ident),
                format: ::viso_gpu::AttrFormat::#fmt,
            }
        });
    }

    quote! {
        // SAFETY: the derive only accepts `#[repr(C)]` structs whose every field
        // is a 4-byte-aligned GPU scalar/vector, so the type is a valid
        // instance-buffer element and `LAYOUT` describes its true offsets.
        unsafe impl #impl_generics ::viso_gpu::GpuInstance for #name #ty_generics #where_clause {
            const STRIDE: usize = ::core::mem::size_of::<Self>();
        }

        impl #impl_generics #name #ty_generics #where_clause {
            /// The explicit per-field GPU instance layout, generated by
            /// `#[derive(GpuInstance)]`.
            pub const LAYOUT: ::viso_gpu::InstanceLayout = ::viso_gpu::InstanceLayout {
                stride: ::core::mem::size_of::<Self>(),
                fields: &[ #(#field_inits),* ],
            };

            /// Validate this instance layout against a shader's declared schema
            /// (offset/format cross-check at pipeline-registration time, §32).
            pub fn validate_against(
                schema: &::viso_gpu::InstanceSchema,
            ) -> ::core::result::Result<(), ::viso_gpu::LayoutError> {
                Self::LAYOUT.validate_against(schema)
            }
        }
    }
}

/// Map a supported field type to its `AttrFormat` variant ident. `None` means
/// the type is not a GPU-uploadable scalar/vector we allow.
fn attr_format(ty: &Type) -> Option<TokenStream> {
    match ty {
        // Scalars.
        Type::Path(p) if p.qself.is_none() => {
            let ident = p.path.get_ident()?;
            match ident.to_string().as_str() {
                "f32" => Some(quote!(Float1)),
                "u32" => Some(quote!(Uint1)),
                _ => None,
            }
        }
        // Fixed-size arrays `[f32; N]` / `[u32; N]`.
        Type::Array(arr) => {
            let elem = match &*arr.elem {
                Type::Path(p) if p.qself.is_none() => p.path.get_ident()?.to_string(),
                _ => return None,
            };
            let len = array_len(&arr.len)?;
            match (elem.as_str(), len) {
                ("f32", 2) => Some(quote!(Float2)),
                ("f32", 3) => Some(quote!(Float3)),
                ("f32", 4) => Some(quote!(Float4)),
                ("u32", 2) => Some(quote!(Uint2)),
                ("u32", 4) => Some(quote!(Uint4)),
                _ => None,
            }
        }
        _ => None,
    }
}

/// Extract a small integer array length from a const expression `[T; N]`.
fn array_len(expr: &syn::Expr) -> Option<usize> {
    if let syn::Expr::Lit(lit) = expr
        && let syn::Lit::Int(int) = &lit.lit
    {
        return int.base10_parse::<usize>().ok();
    }
    None
}

/// Whether the input carries `#[repr(C)]` (possibly alongside other repr hints).
fn has_repr_c(input: &DeriveInput) -> bool {
    input.attrs.iter().any(|attr| {
        if !attr.path().is_ident("repr") {
            return false;
        }
        let mut found = false;
        // `parse_nested_meta` walks `C`, `packed`, `align(N)`, etc.
        let _ = attr.parse_nested_meta(|meta| {
            if meta.path.is_ident("C") {
                found = true;
            }
            // Swallow the argument of `align(N)` so parsing doesn't error.
            if meta.input.peek(syn::token::Paren) {
                let _ = meta.parse_nested_meta(|_| Ok(()));
            }
            Ok(())
        });
        found
    })
}

/// Emit a `compile_error!` at `span` with `msg`.
fn err(span: proc_macro2::Span, msg: &str) -> TokenStream {
    syn::Error::new(span, msg).to_compile_error()
}
