//! `cargo xtask bundle`: package an app binary for a target that cannot run
//! a bare executable.
//!
//! ```text
//! cargo xtask bundle --target android|web -p <package> [--bin <name>] [--release] [--run]
//! ```
//!
//! Android: the binary is linked as a shared library exporting `main` and
//! `JNI_OnLoad`, and packed with the `dev.viso` Java shell into a signed APK
//! (debug keystore) under `<target-dir>/bundle/android/`. `--run` installs it
//! on the device `adb` sees and launches it.
//!
//! Web: the binary is built for `wasm32-unknown-unknown`, its JS glue
//! generated by the `wasm-bindgen` CLI (the version `Cargo.lock` pins), and
//! an `index.html` that loads it written beside them under
//! `<target-dir>/bundle/web/`. `--run` serves the directory on localhost (a
//! secure context, as WebGPU requires) until interrupted.

use std::io::{BufRead, BufReader, Write};
use std::net::{TcpListener, TcpStream};
use std::path::{Path, PathBuf};
use std::process::{Command, ExitCode};

struct Options {
    target: String,
    package: String,
    bin: Option<String>,
    release: bool,
    run: bool,
}

fn parse(args: &[String]) -> Result<Options, String> {
    let mut o = Options {
        target: String::new(),
        package: String::new(),
        bin: None,
        release: false,
        run: false,
    };
    let mut it = args.iter();
    while let Some(arg) = it.next() {
        let mut value = || it.next().cloned().ok_or(format!("{arg} needs a value"));
        match arg.as_str() {
            "--target" => o.target = value()?,
            "-p" | "--package" => o.package = value()?,
            "--bin" => o.bin = Some(value()?),
            "--release" => o.release = true,
            "--run" => o.run = true,
            other => return Err(format!("unknown argument {other:?}")),
        }
    }
    if o.target.is_empty() || o.package.is_empty() {
        return Err("--target and -p are required".into());
    }
    Ok(o)
}

pub(crate) fn bundle(args: &[String]) -> ExitCode {
    let options = match parse(args) {
        Ok(o) => o,
        Err(e) => {
            eprintln!("bundle: {e}\nusage: {USAGE}");
            return ExitCode::FAILURE;
        }
    };
    let result = match options.target.as_str() {
        "android" => android(&options),
        "web" => web(&options),
        other => Err(format!("unknown bundle target {other:?} (android, web)")),
    };
    match result {
        Ok(path) => {
            println!("{}", path.display());
            ExitCode::SUCCESS
        }
        Err(e) => {
            eprintln!("bundle: {e}");
            ExitCode::FAILURE
        }
    }
}

const USAGE: &str =
    "cargo xtask bundle --target android|web -p <package> [--bin <name>] [--release] [--run]";

/// Run `cmd`, failing with its name if it does not succeed.
fn run(cmd: &mut Command) -> Result<(), String> {
    let status = cmd
        .status()
        .map_err(|e| format!("{:?}: {e}", cmd.get_program()))?;
    if status.success() {
        Ok(())
    } else {
        Err(format!("{:?} failed ({status})", cmd.get_program()))
    }
}

/// Run `cmd` and capture its stdout.
fn output(cmd: &mut Command) -> Result<String, String> {
    let out = cmd
        .output()
        .map_err(|e| format!("{:?}: {e}", cmd.get_program()))?;
    if !out.status.success() {
        return Err(format!(
            "{:?} failed: {}",
            cmd.get_program(),
            String::from_utf8_lossy(&out.stderr)
        ));
    }
    Ok(String::from_utf8_lossy(&out.stdout).into_owned())
}

/// The entry of `dir` whose name sorts last by its numeric parts (the
/// newest version), among those `keep` accepts.
fn newest(dir: &Path, keep: impl Fn(&str) -> bool) -> Option<PathBuf> {
    let key = |name: &str| -> Vec<u64> {
        name.split(|c: char| !c.is_ascii_digit())
            .filter(|s| !s.is_empty())
            .filter_map(|s| s.parse().ok())
            .collect()
    };
    std::fs::read_dir(dir)
        .ok()?
        .filter_map(Result::ok)
        .map(|e| e.file_name().to_string_lossy().into_owned())
        .filter(|n| keep(n))
        .max_by_key(|n| key(n))
        .map(|n| dir.join(n))
}

/// The executable path of the `--bin` artifact in cargo's JSON messages.
fn executable(messages: &str) -> Option<PathBuf> {
    messages
        .lines()
        .filter(|l| l.contains("\"reason\":\"compiler-artifact\""))
        .filter_map(|l| {
            let at = l.find("\"executable\":\"")? + "\"executable\":\"".len();
            let end = l[at..].find('"')?;
            Some(PathBuf::from(l[at..at + end].replace("\\\\", "\\")))
        })
        .next_back()
}

struct AndroidSdk {
    ndk_bin: PathBuf,
    build_tools: PathBuf,
    platform_jar: PathBuf,
    adb: PathBuf,
}

fn android_sdk() -> Result<AndroidSdk, String> {
    let home = std::env::var_os("HOME")
        .map(PathBuf::from)
        .unwrap_or_default();
    let sdk = ["ANDROID_HOME", "ANDROID_SDK_ROOT"]
        .iter()
        .find_map(std::env::var_os)
        .map(PathBuf::from)
        .unwrap_or_else(|| home.join("Library/Android/sdk"));
    if !sdk.is_dir() {
        return Err(format!(
            "no Android SDK at {} (set ANDROID_HOME)",
            sdk.display()
        ));
    }
    let ndk = std::env::var_os("ANDROID_NDK_HOME")
        .map(PathBuf::from)
        .or_else(|| newest(&sdk.join("ndk"), |_| true))
        .ok_or("no NDK under $ANDROID_HOME/ndk (set ANDROID_NDK_HOME)")?;
    let prebuilt = newest(&ndk.join("toolchains/llvm/prebuilt"), |_| true)
        .ok_or("NDK has no LLVM toolchain")?;
    let build_tools =
        newest(&sdk.join("build-tools"), |_| true).ok_or("no SDK build-tools installed")?;
    let platform = newest(&sdk.join("platforms"), |n| {
        n.strip_prefix("android-")
            .is_some_and(|v| v.chars().all(|c| c.is_ascii_digit() || c == '.'))
    })
    .ok_or("no SDK platform installed")?;
    Ok(AndroidSdk {
        ndk_bin: prebuilt.join("bin"),
        build_tools,
        platform_jar: platform.join("android.jar"),
        adb: sdk.join("platform-tools/adb"),
    })
}

/// The lowest API level the bundle supports (the manifest's `minSdkVersion`).
const ANDROID_MIN_API: u32 = 26;

fn android(o: &Options) -> Result<PathBuf, String> {
    let root = crate::workspace_root();
    let sdk = android_sdk()?;
    let triple = "aarch64-linux-android";
    let clang = sdk.ndk_bin.join(format!("{triple}{ANDROID_MIN_API}-clang"));
    let bin = o.bin.clone().unwrap_or_else(|| o.package.clone());
    let lib = bin.replace('-', "_");

    // The app, linked as a shared library the activity loads. `main` and
    // `JNI_OnLoad` stay exported (and kept) for the loader and the VM;
    // 16 KiB segments keep it loadable on 16 KiB-page devices.
    let mut cargo = Command::new(std::env::var_os("CARGO").unwrap_or_else(|| "cargo".into()));
    cargo
        .current_dir(&root)
        .args(["rustc", "--message-format=json-render-diagnostics"])
        .args(["-p", &o.package, "--bin", &bin, "--target", triple])
        .args(o.release.then_some("--release"))
        .args(["--", "-A", "linker_messages"])
        .args([
            "-Clink-arg=-shared",
            "-Clink-arg=-Wl,--export-dynamic-symbol=main",
            "-Clink-arg=-Wl,--export-dynamic-symbol=JNI_OnLoad",
            "-Clink-arg=-Wl,-u,JNI_OnLoad",
            "-Clink-arg=-Wl,-z,max-page-size=16384",
        ])
        .env("CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER", &clang)
        .env("CC_aarch64_linux_android", &clang)
        .env("AR_aarch64_linux_android", sdk.ndk_bin.join("llvm-ar"));
    let built = executable(&output(&mut cargo)?).ok_or("cargo reported no executable")?;

    let target_dir = built
        .ancestors()
        .nth(3)
        .ok_or("unexpected artifact path")?
        .to_path_buf();
    let out = target_dir.join("bundle/android").join(&bin);
    let _ = std::fs::remove_dir_all(&out);
    let (classes, dex, stage) = (out.join("classes"), out.join("dex"), out.join("apk"));
    for dir in [&classes, &dex, &stage.join("lib/arm64-v8a")] {
        std::fs::create_dir_all(dir).map_err(|e| format!("{}: {e}", dir.display()))?;
    }
    let so = stage.join(format!("lib/arm64-v8a/lib{lib}.so"));
    std::fs::copy(&built, &so).map_err(|e| format!("{}: {e}", so.display()))?;

    // The Java shell.
    let shell = root.join("crates/platform/android");
    let sources: Vec<PathBuf> = std::fs::read_dir(shell.join("java/dev/viso"))
        .map_err(|e| e.to_string())?
        .filter_map(Result::ok)
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|x| x == "java"))
        .collect();
    run(Command::new("javac")
        .args([
            "-source",
            "8",
            "-target",
            "8",
            "-Xlint:-options",
            "-encoding",
            "UTF-8",
        ])
        .arg("-classpath")
        .arg(&sdk.platform_jar)
        .arg("-d")
        .arg(&classes)
        .args(&sources))?;
    let class_files: Vec<PathBuf> = std::fs::read_dir(classes.join("dev/viso"))
        .map_err(|e| e.to_string())?
        .filter_map(Result::ok)
        .map(|e| e.path())
        .collect();
    run(Command::new(sdk.build_tools.join("d8"))
        .args(["--min-api", &ANDROID_MIN_API.to_string()])
        .args(o.release.then_some("--release"))
        .arg("--lib")
        .arg(&sdk.platform_jar)
        .arg("--output")
        .arg(&dex)
        .args(&class_files))?;
    std::fs::copy(dex.join("classes.dex"), stage.join("classes.dex")).map_err(|e| e.to_string())?;

    // Manifest, resource table, then the payload.
    let package = format!("dev.viso.{lib}");
    let manifest = std::fs::read_to_string(shell.join("AndroidManifest.xml"))
        .map_err(|e| e.to_string())?
        .replace("{package}", &package)
        .replace("{label}", &bin)
        .replace("{lib}", &lib);
    let manifest_path = out.join("AndroidManifest.xml");
    std::fs::write(&manifest_path, manifest).map_err(|e| e.to_string())?;
    let unaligned = out.join("unaligned.apk");
    run(Command::new(sdk.build_tools.join("aapt2"))
        .arg("link")
        .arg("-I")
        .arg(&sdk.platform_jar)
        .arg("--manifest")
        .arg(&manifest_path)
        .arg("-o")
        .arg(&unaligned))?;
    // The native library is stored, so it can be mapped from the APK.
    run(Command::new("zip")
        .current_dir(&stage)
        .args(["-q", "-0", "-r"])
        .arg(&unaligned)
        .arg("lib"))?;
    run(Command::new("zip")
        .current_dir(&stage)
        .arg("-q")
        .arg(&unaligned)
        .arg("classes.dex"))?;
    let apk = out.join(format!("{bin}.apk"));
    run(Command::new(sdk.build_tools.join("zipalign"))
        .args(["-P", "16", "-f", "4"])
        .arg(&unaligned)
        .arg(&apk))?;
    let keystore = debug_keystore()?;
    run(Command::new(sdk.build_tools.join("apksigner"))
        .args(["sign", "--ks"])
        .arg(&keystore)
        .args([
            "--ks-pass",
            "pass:android",
            "--ks-key-alias",
            "androiddebugkey",
        ])
        .arg(&apk))?;

    if o.run {
        run(Command::new(&sdk.adb).args(["install", "-r"]).arg(&apk))?;
        run(Command::new(&sdk.adb).args([
            "shell",
            "am",
            "start",
            "-n",
            &format!("{package}/dev.viso.VisoActivity"),
        ]))?;
    }
    Ok(apk)
}

/// The page that loads the app: the canvas fills it edge to edge (the
/// backend keeps content inside the safe area) and nothing scrolls.
fn index_html(bin: &str) -> String {
    format!(
        r#"<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<title>{bin}</title>
<style>html, body {{ height: 100%; margin: 0; overflow: hidden; overscroll-behavior: none; }}</style>
</head>
<body>
<script type="module">import init from "./{bin}.js"; init();</script>
</body>
</html>
"#
    )
}

fn web(o: &Options) -> Result<PathBuf, String> {
    let root = crate::workspace_root();
    let bin = o.bin.clone().unwrap_or_else(|| o.package.clone());
    let mut cargo = Command::new(std::env::var_os("CARGO").unwrap_or_else(|| "cargo".into()));
    cargo
        .current_dir(&root)
        .args(["build", "--message-format=json-render-diagnostics"])
        .args([
            "-p",
            &o.package,
            "--bin",
            &bin,
            "--target",
            "wasm32-unknown-unknown",
        ])
        .args(o.release.then_some("--release"));
    let built = executable(&output(&mut cargo)?).ok_or("cargo reported no executable")?;

    let target_dir = built.ancestors().nth(3).ok_or("unexpected artifact path")?;
    let out = target_dir.join("bundle/web").join(&bin);
    let _ = std::fs::remove_dir_all(&out);
    std::fs::create_dir_all(&out).map_err(|e| format!("{}: {e}", out.display()))?;
    run(Command::new("wasm-bindgen")
        .args(["--target", "web", "--no-typescript", "--out-name", &bin])
        .arg("--out-dir")
        .arg(&out)
        .arg(&built))
    .map_err(|e| format!("{e} (install the CLI: cargo install wasm-bindgen-cli)"))?;
    let index = out.join("index.html");
    std::fs::write(&index, index_html(&bin)).map_err(|e| format!("{}: {e}", index.display()))?;

    if o.run {
        serve(&out)?;
    }
    Ok(index)
}

/// The `Content-Type` of a bundle file (`.wasm` must be `application/wasm`
/// for streaming compilation).
fn mime(path: &Path) -> &'static str {
    match path.extension().and_then(|x| x.to_str()) {
        Some("html") => "text/html; charset=utf-8",
        Some("js") => "text/javascript; charset=utf-8",
        Some("wasm") => "application/wasm",
        Some("css") => "text/css; charset=utf-8",
        Some("png") => "image/png",
        Some("json") => "application/json",
        _ => "application/octet-stream",
    }
}

/// The file under `dir` a request target names: `/` is the index; anything
/// that could leave `dir` is refused.
fn resolve(dir: &Path, target: &str) -> Option<PathBuf> {
    let path = target.split(['?', '#']).next()?.trim_start_matches('/');
    let path = if path.is_empty() { "index.html" } else { path };
    let safe = path
        .split('/')
        .all(|part| !part.is_empty() && part != "." && part != ".." && !part.contains('\\'));
    safe.then(|| dir.join(path))
}

/// Serve `dir` on the first free localhost port from 8000, one request at
/// a time, until the process is interrupted.
fn serve(dir: &Path) -> Result<(), String> {
    let listener = (8000..8100)
        .find_map(|port| TcpListener::bind(("127.0.0.1", port)).ok())
        .ok_or("no free port in 8000..8100")?;
    let addr = listener.local_addr().map_err(|e| e.to_string())?;
    println!("serving {} at http://{addr}/ (Ctrl-C stops)", dir.display());
    for stream in listener.incoming().filter_map(Result::ok) {
        let _ = respond(dir, stream);
    }
    Ok(())
}

fn respond(dir: &Path, mut stream: TcpStream) -> std::io::Result<()> {
    let mut request = String::new();
    BufReader::new(&stream).read_line(&mut request)?;
    let mut words = request.split_whitespace();
    let (method, target) = (words.next().unwrap_or(""), words.next().unwrap_or(""));
    let file = (method == "GET" || method == "HEAD")
        .then(|| resolve(dir, target))
        .flatten()
        .and_then(|path| std::fs::read(&path).ok().map(|body| (path, body)));
    let (status, kind, body) = match file {
        Some((path, body)) => ("200 OK", mime(&path), body),
        None => ("404 Not Found", "text/plain", b"not found".to_vec()),
    };
    write!(
        stream,
        "HTTP/1.1 {status}\r\nContent-Type: {kind}\r\nContent-Length: {}\r\nCache-Control: no-store\r\nConnection: close\r\n\r\n",
        body.len()
    )?;
    if method != "HEAD" {
        stream.write_all(&body)?;
    }
    stream.flush()
}

/// The standard Android debug keystore, created if missing.
fn debug_keystore() -> Result<PathBuf, String> {
    let home = std::env::var_os("HOME")
        .map(PathBuf::from)
        .ok_or("HOME is not set")?;
    let dir = home.join(".android");
    let keystore = dir.join("debug.keystore");
    if keystore.exists() {
        return Ok(keystore);
    }
    std::fs::create_dir_all(&dir).map_err(|e| e.to_string())?;
    run(Command::new("keytool")
        .args(["-genkeypair", "-keystore"])
        .arg(&keystore)
        .args([
            "-storepass",
            "android",
            "-keypass",
            "android",
            "-alias",
            "androiddebugkey",
            "-keyalg",
            "RSA",
            "-keysize",
            "2048",
            "-validity",
            "10000",
            "-dname",
            "CN=Android Debug,O=Android,C=US",
        ]))?;
    Ok(keystore)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_bundle_arguments() {
        let args: Vec<String> = ["--target", "android", "-p", "app", "--release"]
            .iter()
            .map(|s| s.to_string())
            .collect();
        let o = parse(&args).unwrap();
        assert_eq!((o.target.as_str(), o.package.as_str()), ("android", "app"));
        assert!(o.release && !o.run && o.bin.is_none());
        assert!(parse(&args[..2]).is_err());
        assert!(parse(&["--frobnicate".to_string()]).is_err());
    }

    #[test]
    fn the_page_loads_the_generated_module() {
        let html = index_html("demo");
        assert!(html.contains(r#"import init from "./demo.js"; init();"#));
        assert!(html.contains("viewport-fit=cover"));
    }

    #[test]
    fn served_files_have_their_types_and_stay_in_the_bundle() {
        assert_eq!(mime(Path::new("a/app_bg.wasm")), "application/wasm");
        assert_eq!(mime(Path::new("app.js")), "text/javascript; charset=utf-8");
        assert_eq!(mime(Path::new("index.html")), "text/html; charset=utf-8");
        assert_eq!(mime(Path::new("blob")), "application/octet-stream");
        let dir = Path::new("/b");
        assert_eq!(resolve(dir, "/"), Some(dir.join("index.html")));
        assert_eq!(resolve(dir, "/app.js?v=1"), Some(dir.join("app.js")));
        assert_eq!(resolve(dir, "/../secret"), None);
        assert_eq!(resolve(dir, "/a//b"), None);
        assert_eq!(resolve(dir, "/a\\..\\b"), None);
    }

    #[test]
    fn finds_the_last_executable() {
        let messages = concat!(
            "{\"reason\":\"compiler-artifact\",\"executable\":null}\n",
            "{\"reason\":\"compiler-artifact\",\"executable\":\"/t/aarch64-linux-android/debug/app\"}\n",
            "{\"reason\":\"build-finished\",\"success\":true}\n",
        );
        assert_eq!(
            executable(messages),
            Some(PathBuf::from("/t/aarch64-linux-android/debug/app"))
        );
    }

    #[test]
    fn newest_orders_versions_numerically() {
        let dir = std::env::temp_dir().join(format!("xtask-newest-{}", std::process::id()));
        for v in ["9.0.0", "36.1.0", "37.0.0", "android-36", "android-36.1"] {
            std::fs::create_dir_all(dir.join(v)).unwrap();
        }
        let digits = |n: &str| n.starts_with(|c: char| c.is_ascii_digit());
        assert_eq!(newest(&dir, digits), Some(dir.join("37.0.0")));
        assert_eq!(
            newest(&dir, |n| n.starts_with("android-")),
            Some(dir.join("android-36.1"))
        );
        std::fs::remove_dir_all(&dir).unwrap();
    }
}
