//! The runtime of chunks compiled to Rust (`crate::aot`): what the lowered
//! code of each op calls, with the interpreter's semantics.
//!
//! Lowered code keeps a chunk's registers in Rust locals and its control flow
//! in a block machine; every op spends one unit of fuel first ([`tick`]), and
//! a fault records where the interpreter's cursor would have been ([`at`]),
//! so a compiled invocation spends, faults and rolls back exactly as an
//! interpreted one.

use std::fmt;
use std::mem;
use std::rc::Rc;

use super::{Event, Instance, Memo, Step, Vm};
use crate::arith;
use crate::module::{Module, TaskPolicy};
use crate::op::{ArithOp, DisplayKind, Num};
use crate::value::{Aggregate, Closure, Value};
use crate::vm::{FaultKind, Start};

/// A chunk compiled to Rust: the VM, the instance, the call depth, the
/// arguments and the captured values.
pub type NativeFn = fn(&mut Vm, &mut Instance, usize, &[Value], &[Value]) -> Step<Value>;

/// The chunks of one build compiled to Rust, generated by
/// [`lower_systems`](crate::aot::lower_systems) and installed with
/// [`Vm::install_native`].
#[derive(Debug)]
pub struct NativeCode {
    /// The hash of the module the code was lowered from.
    pub build: u64,
    /// Each compiled chunk, by index.
    pub chunks: &'static [(u32, NativeFn)],
}

/// Compiled code lowered from another build than the module it was
/// installed for.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct NativeCodeMismatch {
    /// The module's build hash.
    pub expected: u64,
    /// The build hash the code was lowered from.
    pub found: u64,
}

impl fmt::Display for NativeCodeMismatch {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "the compiled systems were lowered from build {:#018x}, not this module's {:#018x}",
            self.found, self.expected
        )
    }
}

impl std::error::Error for NativeCodeMismatch {}

/// The build hash of `module`: 64-bit FNV-1a of its encoding, the hash a
/// game's snapshots carry.
pub fn build_hash(module: &Module) -> u64 {
    module.encode().iter().fold(0xcbf2_9ce4_8422_2325, |h, &b| {
        (h ^ u64::from(b)).wrapping_mul(0x0100_0000_01b3)
    })
}

/// One step of a [`set_path`] write.
#[derive(Debug, Clone, Copy)]
pub enum PathStep<'a> {
    /// Field `index` of an aggregate.
    Field(u32),
    /// The list element at the index this register holds.
    Index(&'a Value),
}

/// Spends one unit of fuel for the next op.
#[inline(always)]
pub fn tick(vm: &mut Vm) -> Step<()> {
    if vm.fuel == 0 {
        return Err(FaultKind::InstructionBudget);
    }
    vm.fuel -= 1;
    Ok(())
}

/// Records that `kind` faulted in `chunk` with the interpreter's cursor at
/// `pc`, unless a callee already recorded where it faulted.
#[cold]
pub fn at(vm: &mut Vm, chunk: u32, pc: usize, kind: FaultKind) -> FaultKind {
    if vm.native_at.is_none() {
        vm.native_at = Some((chunk, pc));
    }
    kind
}

/// The module `vm` runs.
#[inline]
pub fn module(vm: &Vm) -> Rc<Module> {
    Rc::clone(&vm.module)
}

/// The constant pool of `chunk`.
#[inline]
pub fn consts(module: &Module, chunk: u32) -> &[Value] {
    match &module.chunk(chunk).body {
        Ok(code) => &code.consts,
        Err(_) => &[],
    }
}

/// An integer register.
#[inline(always)]
pub fn int(v: &Value) -> Step<i64> {
    v.as_int().ok_or(FaultKind::Internal)
}

/// A float register.
#[inline(always)]
pub fn float(v: &Value) -> Step<f64> {
    v.as_float().ok_or(FaultKind::Internal)
}

/// `state[slot]`.
#[inline]
pub fn load_state(inst: &Instance, slot: u32) -> Step<Value> {
    inst.states
        .get(slot as usize)
        .cloned()
        .ok_or(FaultKind::Internal)
}

/// `state[slot] = value`, undone if the transaction faults.
#[inline]
pub fn store_state(vm: &mut Vm, inst: &mut Instance, slot: u32, value: Value) -> Step<()> {
    let Some(target) = inst.states.get_mut(slot as usize) else {
        return Err(FaultKind::Internal);
    };
    let (word, bit) = (slot as usize / 64, 1u64 << (slot % 64));
    if vm.marks[word] & bit == 0 {
        vm.marks[word] |= bit;
        vm.undo.push((slot, mem::replace(target, value)));
    } else {
        *target = value;
    }
    if vm.memo {
        inst.forget_state(slot as usize);
    }
    Ok(())
}

/// `input[slot]`.
#[inline]
pub fn load_input(inst: &Instance, slot: u32) -> Step<Value> {
    inst.inputs
        .get(slot as usize)
        .cloned()
        .ok_or(FaultKind::Internal)
}

/// A typed binary operator.
#[inline]
pub fn arith(op: ArithOp, a: &Value, b: &Value) -> Step<Value> {
    arith::binary(op, a, b)
}

/// `-v`.
#[inline]
pub fn neg(num: Num, v: &Value) -> Step<Value> {
    arith::neg(num, v)
}

/// `!v`, the bitwise complement.
#[inline]
pub fn bit_not(num: Num, v: &Value) -> Step<Value> {
    arith::bit_not(num, v)
}

/// `v as to`.
#[inline]
pub fn cast(from: Num, to: Num, v: &Value) -> Step<Value> {
    arith::cast(from, to, v)
}

/// The cached value of `func` when it is a cached computed already
/// evaluated, marking it evaluating otherwise; `None` means call it.
///
/// # Errors
///
/// [`FaultKind::ReactiveCycle`] for a computed reached while it evaluates.
#[inline]
pub fn memo_enter(vm: &mut Vm, inst: &mut Instance, func: u32) -> Step<Option<Value>> {
    if !vm.memo {
        return Ok(None);
    }
    let Some(entry) = vm.graph.entry(func) else {
        return Ok(None);
    };
    match &inst.memo[entry] {
        Memo::Ready(value) => Ok(Some(value.clone())),
        Memo::Evaluating => {
            let name = vm.module.chunk(func).name.to_string();
            vm.trap(
                FaultKind::ReactiveCycle,
                format!("computed `{name}` depends on itself"),
            )
        }
        Memo::Empty => {
            inst.memo[entry] = Memo::Evaluating;
            Ok(None)
        }
    }
}

/// Returns `value` from `chunk`, caching it when `chunk` is a cached
/// computed.
#[inline]
pub fn ret(vm: &mut Vm, inst: &mut Instance, chunk: u32, value: Value) -> Value {
    if vm.memo
        && let Some(entry) = vm.graph.entry(chunk)
    {
        inst.memo[entry] = Memo::Ready(value.clone());
    }
    value
}

/// Checks that a call from depth `depth` stays within the call depth.
#[inline]
pub fn depth(vm: &Vm, depth: usize) -> Step<()> {
    if depth + 2 > vm.budget.depth as usize {
        return Err(FaultKind::CallDepth);
    }
    Ok(())
}

/// The fault of calling `func`, which has no body.
#[cold]
pub fn unsupported(vm: &mut Vm, func: u32) -> FaultKind {
    let module = Rc::clone(&vm.module);
    match vm.body(&module, func) {
        Ok(_) => FaultKind::Internal,
        Err(kind) => kind,
    }
}

/// The fault of reaching unreachable code.
#[cold]
pub fn unreachable(vm: &mut Vm) -> FaultKind {
    vm.detail = "reached unreachable code".into();
    FaultKind::Internal
}

/// Calls the closure `callee` with `args` from depth `depth`, through the
/// installed code.
pub fn call_value(
    vm: &mut Vm,
    inst: &mut Instance,
    depth: usize,
    callee: &Value,
    args: &[Value],
) -> Step<Value> {
    let Value::Closure(closure) = callee else {
        return Err(FaultKind::Internal);
    };
    let closure = Rc::clone(closure);
    let module = Rc::clone(&vm.module);
    let Some(chunk) = module.chunks().get(closure.func as usize) else {
        return Err(FaultKind::Internal);
    };
    if usize::from(chunk.params) != args.len() || chunk.captures.len() != closure.captures.len() {
        return Err(FaultKind::Internal);
    }
    vm.body(&module, closure.func)?;
    self::depth(vm, depth)?;
    let Some(Some(function)) = vm.native.get(closure.func as usize).copied() else {
        return vm.trap(
            FaultKind::Internal,
            format!("`{}` has no compiled code", chunk.name),
        );
    };
    function(vm, inst, depth + 1, args, &closure.captures)
}

/// The native call scratch, empty, to gather a call's arguments into.
#[inline]
pub fn scratch(vm: &mut Vm) -> Vec<Value> {
    let mut args = mem::take(&mut vm.native_args);
    args.clear();
    args
}

/// Calls native import `import` with `args`, gathered into [`scratch`].
#[inline]
pub fn native(vm: &mut Vm, import: u32, args: Vec<Value>) -> Step<Value> {
    let value = vm.call_import(import as usize, args)?;
    if vm.awaiting.take().is_some() {
        return vm.trap(
            FaultKind::Internal,
            "a task native was awaited outside a task".into(),
        );
    }
    Ok(value)
}

/// A closure of `func` over `captures`.
pub fn closure(vm: &mut Vm, func: u32, captures: Box<[Value]>) -> Step<Value> {
    vm.charge(24 + 16 * captures.len() as u64)?;
    Ok(Value::Closure(Rc::new(Closure { func, captures })))
}

/// An aggregate of `tag` with `fields`.
pub fn make(vm: &mut Vm, tag: u32, fields: Box<[Value]>) -> Step<Value> {
    vm.charge(24 + 16 * fields.len() as u64)?;
    Ok(Value::Agg(Rc::new(Aggregate { tag, fields })))
}

/// A list of `items`.
pub fn list(vm: &mut Vm, items: Vec<Value>) -> Step<Value> {
    vm.charge(16 + 16 * items.len() as u64)?;
    Ok(Value::List(Rc::new(items)))
}

/// The concatenation of the strings `parts`.
pub fn concat(vm: &mut Vm, parts: &[&Value]) -> Step<Value> {
    let mut len = 0;
    for part in parts {
        len += part.as_str().ok_or(FaultKind::Internal)?.len();
    }
    vm.charge(16 + len as u64)?;
    let mut text = String::with_capacity(len);
    for part in parts {
        text.push_str(part.as_str().unwrap_or_default());
    }
    Ok(Value::Str(Rc::new(text)))
}

/// The catalog's `message` for the reader of `locale` with `args`, gathered
/// into [`scratch`].
pub fn translate(vm: &mut Vm, message: &Value, locale: &Value, args: Vec<Value>) -> Step<Value> {
    vm.translate(message, locale, args)
}

/// Field `index` of the aggregate `v`.
#[inline]
pub fn field(v: &Value, index: u16) -> Step<Value> {
    let Value::Agg(agg) = v else {
        return Err(FaultKind::Internal);
    };
    agg.fields
        .get(usize::from(index))
        .cloned()
        .ok_or(FaultKind::Internal)
}

/// `list[index]`.
#[inline]
pub fn index(vm: &mut Vm, list: &Value, index: &Value) -> Step<Value> {
    let i = int(index)?;
    let Value::List(items) = list else {
        return Err(FaultKind::Internal);
    };
    match usize::try_from(i).ok().and_then(|i| items.get(i)) {
        Some(item) => Ok(item.clone()),
        None => {
            let len = items.len();
            vm.trap(
                FaultKind::IndexOutOfBounds,
                format!("index {i} is out of bounds of a list of {len}"),
            )
        }
    }
}

/// The length of the list `v`.
#[inline]
pub fn len(v: &Value) -> Step<Value> {
    let Value::List(items) = v else {
        return Err(FaultKind::Internal);
    };
    Ok(Value::Int(items.len() as i64))
}

/// The elements of the list `list` to edit in place, copied first when
/// another value shares them.
fn items_mut<'v>(vm: &mut Vm, list: &'v mut Value) -> Step<&'v mut Vec<Value>> {
    let bytes = list.heap_bytes();
    let Value::List(items) = list else {
        return Err(FaultKind::Internal);
    };
    if Rc::strong_count(items) > 1 {
        vm.charge(bytes)?;
    }
    Ok(Rc::make_mut(items))
}

/// The bytes one more list element takes.
const SLOT_BYTES: u64 = mem::size_of::<Value>() as u64;

/// The position `index` holds, if it lies within `0..=len` (`0..len` without
/// `end`); else the out-of-bounds fault.
fn position(vm: &mut Vm, index: &Value, len: usize, end: bool) -> Step<usize> {
    let i = int(index)?;
    match usize::try_from(i)
        .ok()
        .filter(|&i| i < len || (end && i == len))
    {
        Some(i) => Ok(i),
        None => vm.trap(
            FaultKind::IndexOutOfBounds,
            format!("index {i} is out of bounds of a list of {len}"),
        ),
    }
}

/// Appends `item` to the list `list`.
pub fn push(vm: &mut Vm, list: &mut Value, item: Value) -> Step<()> {
    vm.charge(SLOT_BYTES)?;
    items_mut(vm, list)?.push(item);
    Ok(())
}

/// Inserts `item` before position `index` of the list `list`.
pub fn insert(vm: &mut Vm, list: &mut Value, index: &Value, item: Value) -> Step<()> {
    let len = list_len(list)?;
    let at = position(vm, index, len, true)?;
    vm.charge(SLOT_BYTES)?;
    items_mut(vm, list)?.insert(at, item);
    Ok(())
}

/// Removes and returns the element at `index` of the list `list`.
pub fn remove(vm: &mut Vm, list: &mut Value, index: &Value) -> Step<Value> {
    let len = list_len(list)?;
    let at = position(vm, index, len, false)?;
    Ok(items_mut(vm, list)?.remove(at))
}

/// Shortens the list `list` to `len` elements; a negative length empties it.
pub fn truncate(vm: &mut Vm, list: &mut Value, len: &Value) -> Step<()> {
    let keep = usize::try_from(int(len)?).unwrap_or(0);
    if keep < list_len(list)? {
        items_mut(vm, list)?.truncate(keep);
    }
    Ok(())
}

fn list_len(list: &Value) -> Step<usize> {
    match list {
        Value::List(items) => Ok(items.len()),
        _ => Err(FaultKind::Internal),
    }
}

/// The variant tag of `v`.
#[inline]
pub fn tag(v: &Value) -> Step<Value> {
    match v {
        Value::Agg(agg) => Ok(Value::Int(i64::from(agg.tag))),
        Value::Int(tag) => Ok(Value::Int(*tag)),
        _ => Err(FaultKind::Internal),
    }
}

/// The text of `v`.
pub fn display(vm: &mut Vm, kind: DisplayKind, v: &Value) -> Step<Value> {
    if kind == DisplayKind::Str {
        if v.as_str().is_none() {
            return Err(FaultKind::Internal);
        }
        return Ok(v.clone());
    }
    let text = arith::display(kind, v)?;
    vm.charge(16 + text.len() as u64)?;
    Ok(Value::str(text))
}

/// The text of the dimensional scalar `v` followed by `suffix`.
pub fn display_dim(vm: &mut Vm, v: &Value, suffix: &str) -> Step<Value> {
    let text = arith::display_dim(v, suffix)?;
    vm.charge(16 + text.len() as u64)?;
    Ok(Value::str(text))
}

/// Writes `src` into `root` at `steps`, copying shared parts.
pub fn set_path(vm: &mut Vm, root: &mut Value, steps: &[PathStep<'_>], src: Value) -> Step<()> {
    let mut slot = root;
    for step in steps {
        let shared = match &*slot {
            Value::Agg(agg) => Rc::strong_count(agg) > 1,
            Value::List(items) => Rc::strong_count(items) > 1,
            _ => return Err(FaultKind::Internal),
        };
        if shared {
            vm.charge(slot.heap_bytes())?;
        }
        slot = match (step, slot) {
            (PathStep::Field(i), Value::Agg(agg)) => Rc::make_mut(agg)
                .fields
                .get_mut(*i as usize)
                .ok_or(FaultKind::Internal)?,
            (PathStep::Index(at), Value::List(items)) => {
                let i = at.as_int().ok_or(FaultKind::Internal)?;
                let len = items.len();
                match usize::try_from(i).ok().filter(|&i| i < len) {
                    Some(i) => &mut Rc::make_mut(items)[i],
                    None => {
                        return vm.trap(
                            FaultKind::IndexOutOfBounds,
                            format!("index {i} is out of bounds of a list of {len}"),
                        );
                    }
                }
            }
            _ => return Err(FaultKind::Internal),
        };
    }
    *slot = src;
    Ok(())
}

/// Queues event `index` with `args`.
pub fn emit(vm: &mut Vm, index: u32, args: Box<[Value]>) -> Step<()> {
    vm.charge(16 + 16 * args.len() as u64)?;
    vm.events.push(Event { index, args });
    Ok(())
}

/// Queues the start of task `task`, as [`Op::Start`](crate::Op::Start)
/// describes.
#[allow(clippy::too_many_arguments)]
pub fn start(
    vm: &mut Vm,
    task: u32,
    args: Box<[Value]>,
    done: Option<Value>,
    cancelled: Option<Value>,
    instance: u32,
    slot: u32,
    policy: u32,
) -> Step<()> {
    vm.charge(64 + 16 * args.len() as u64)?;
    vm.starts.push(Start {
        task,
        args,
        done,
        cancelled,
        instance,
        slot: (slot != u32::MAX).then_some(slot),
        policy: TaskPolicy::from_word(policy),
    });
    Ok(())
}
