//! Generated by `lower_systems` from build 0xed61d717163ad3d0: the systems'
//! chunks compiled to Rust. Do not edit; regenerate from the module.

#![allow(unused_mut, unused_variables, unused_assignments, unused_imports)]
#![allow(unreachable_code, unreachable_patterns, non_snake_case)]
#![allow(clippy::all, clippy::pedantic, clippy::nursery)]

use viso_behavior::aot::{self as rt, NativeCode, PathStep};
use viso_behavior::{Arith, ArithOp, DisplayKind, FaultKind, Instance, Num, Value, Vm};

macro_rules! t {
    ($vm:ident, $c:expr, $pc:expr, $e:expr) => {
        match $e {
            Ok(v) => v,
            Err(k) => return Err(rt::at($vm, $c, $pc, k)),
        }
    };
}

/// The compiled chunks, for `Vm::install_native`.
pub static NATIVE: NativeCode = NativeCode {
    build: 0xed61d717163ad3d0,
    chunks: &[
        (0, s0),
        (1, s1),
        (2, s2),
        (3, s3),
        (4, s4),
        (5, s5),
    ],
};

/// "steer" (chunk 0).
fn c0(vm: &mut Vm, inst: &mut Instance, depth: usize, mut r0: Value, mut r1: Value, mut r2: Value) -> Result<Value, FaultKind> {
    let mut r3 = Value::Nil;
    let mut r4 = Value::Nil;
    let mut r5 = Value::Nil;
    let mut r6 = Value::Nil;
    let mut r7 = Value::Nil;
    let mut r8 = Value::Nil;
    let mut r9 = Value::Nil;
    let mut r10 = Value::Nil;
    let mut r11 = Value::Nil;
    let mut r12 = Value::Nil;
    let mut r13 = Value::Nil;
    let mut r14 = Value::Nil;
    let mut r15 = Value::Nil;
    let mut r16 = Value::Nil;
    let mut r17 = Value::Nil;
    let mut r18 = Value::Nil;
    let mut r19 = Value::Nil;
    let mut r20 = Value::Nil;
    let mut r21 = Value::Nil;
    let mut r22 = Value::Nil;
    let mut r23 = Value::Nil;
    let mut r24 = Value::Nil;
    let mut r25 = Value::Nil;
    let mut pc: u32 = 0;
    loop {
        match pc {
            0 => {
                t!(vm, 0, 0, rt::tick(vm));
                r3 = t!(vm, 0, 1, rt::field(&r0, 0));
                t!(vm, 0, 1, rt::tick(vm));
                r4 = Value::Float(t!(vm, 0, 2, rt::float(&r1)) - t!(vm, 0, 2, rt::float(&r3)));
                t!(vm, 0, 2, rt::tick(vm));
                r5 = Value::Float(f64::from_bits(0x3fa999999999999a));
                t!(vm, 0, 3, rt::tick(vm));
                r6 = Value::Float(t!(vm, 0, 4, rt::float(&r4)) * t!(vm, 0, 4, rt::float(&r5)));
                t!(vm, 0, 4, rt::tick(vm));
                r7 = t!(vm, 0, 5, rt::field(&r0, 2));
                t!(vm, 0, 5, rt::tick(vm));
                r8 = Value::Int(7);
                t!(vm, 0, 6, rt::tick(vm));
                r9 = Value::Int(t!(vm, 0, 7, t!(vm, 0, 7, rt::int(&r7)).checked_mul(t!(vm, 0, 7, rt::int(&r8))).ok_or(FaultKind::Overflow)));
                t!(vm, 0, 7, rt::tick(vm));
                r10 = Value::Int(t!(vm, 0, 8, t!(vm, 0, 8, rt::int(&r9)).checked_add(t!(vm, 0, 8, rt::int(&r2))).ok_or(FaultKind::Overflow)));
                t!(vm, 0, 8, rt::tick(vm));
                r11 = Value::Int(17);
                t!(vm, 0, 9, rt::tick(vm));
                r12 = t!(vm, 0, 10, rt::arith(ArithOp::new(Arith::Rem, Num::I64), &r10, &r11));
                t!(vm, 0, 10, rt::tick(vm));
                r13 = t!(vm, 0, 11, rt::field(&r0, 1));
                t!(vm, 0, 11, rt::tick(vm));
                r14 = Value::Float(f64::from_bits(0x3feccccccccccccd));
                t!(vm, 0, 12, rt::tick(vm));
                r15 = Value::Float(t!(vm, 0, 13, rt::float(&r13)) * t!(vm, 0, 13, rt::float(&r14)));
                t!(vm, 0, 13, rt::tick(vm));
                r16 = Value::Float(t!(vm, 0, 14, rt::float(&r15)) + t!(vm, 0, 14, rt::float(&r6)));
                t!(vm, 0, 14, rt::tick(vm));
                r17 = t!(vm, 0, 15, rt::cast(Num::I64, Num::F64, &r12));
                t!(vm, 0, 15, rt::tick(vm));
                r18 = Value::Float(f64::from_bits(0x4020000000000000));
                t!(vm, 0, 16, rt::tick(vm));
                r19 = Value::Float(t!(vm, 0, 17, rt::float(&r17)) - t!(vm, 0, 17, rt::float(&r18)));
                t!(vm, 0, 17, rt::tick(vm));
                r20 = Value::Float(f64::from_bits(0x3f847ae147ae147b));
                t!(vm, 0, 18, rt::tick(vm));
                r21 = Value::Float(t!(vm, 0, 19, rt::float(&r19)) * t!(vm, 0, 19, rt::float(&r20)));
                t!(vm, 0, 19, rt::tick(vm));
                r22 = Value::Float(t!(vm, 0, 20, rt::float(&r16)) + t!(vm, 0, 20, rt::float(&r21)));
                t!(vm, 0, 20, rt::tick(vm));
                r23 = t!(vm, 0, 21, rt::field(&r0, 0));
                t!(vm, 0, 21, rt::tick(vm));
                r24 = Value::Float(t!(vm, 0, 22, rt::float(&r23)) + t!(vm, 0, 22, rt::float(&r22)));
                t!(vm, 0, 22, rt::tick(vm));
                r25 = t!(vm, 0, 23, rt::make(vm, 0, Box::from([r24.clone(), r22.clone(), r12.clone()])));
                t!(vm, 0, 23, rt::tick(vm));
                return Ok(rt::ret(vm, inst, 0, std::mem::take(&mut r25)));
            }
            _ => return Err(rt::at(vm, 0, 0, FaultKind::Internal)),
        }
    }
}

fn s0(vm: &mut Vm, inst: &mut Instance, depth: usize, args: &[Value], caps: &[Value]) -> Result<Value, FaultKind> {
    c0(vm, inst, depth, args[0].clone(), args[1].clone(), args[2].clone())
}

/// "Crowd.fixed_update" (chunk 1).
fn c1(vm: &mut Vm, inst: &mut Instance, depth: usize, mut r0: Value) -> Result<Value, FaultKind> {
    let mut r1 = Value::Nil;
    let mut r2 = Value::Nil;
    let mut r3 = Value::Nil;
    let mut r4 = Value::Nil;
    let mut r5 = Value::Nil;
    let mut r6 = Value::Nil;
    let mut r7 = Value::Nil;
    let mut r8 = Value::Nil;
    let mut r9 = Value::Nil;
    let mut r10 = Value::Nil;
    let mut r11 = Value::Nil;
    let mut r12 = Value::Nil;
    let mut r13 = Value::Nil;
    let mut r14 = Value::Nil;
    let mut r15 = Value::Nil;
    let mut r16 = Value::Nil;
    let mut r17 = Value::Nil;
    let mut r18 = Value::Nil;
    let mut r19 = Value::Nil;
    let mut r20 = Value::Nil;
    let mut r21 = Value::Nil;
    let mut r22 = Value::Nil;
    let mut r23 = Value::Nil;
    let mut r24 = Value::Nil;
    let mut r25 = Value::Nil;
    let mut r26 = Value::Nil;
    let mut r27 = Value::Nil;
    let mut r28 = Value::Nil;
    let mut r29 = Value::Nil;
    let mut r30 = Value::Nil;
    let mut r31 = Value::Nil;
    let mut r32 = Value::Nil;
    let mut r33 = Value::Nil;
    let mut r34 = Value::Nil;
    let mut r35 = Value::Nil;
    let mut r36 = Value::Nil;
    let mut r37 = Value::Nil;
    let mut r38 = Value::Nil;
    let mut r39 = Value::Nil;
    let mut r40 = Value::Nil;
    let mut r41 = Value::Nil;
    let mut r42 = Value::Nil;
    let mut pc: u32 = 0;
    loop {
        match pc {
            0 => {
                t!(vm, 1, 0, rt::tick(vm));
                { let mut a = rt::scratch(vm); a.push(r0.clone()); r1 = t!(vm, 1, 1, rt::native(vm, 0, a)); }
                t!(vm, 1, 1, rt::tick(vm));
                r2 = Value::Int(0);
                t!(vm, 1, 2, rt::tick(vm));
                r3 = t!(vm, 1, 3, rt::load_state(inst, 2));
                t!(vm, 1, 3, rt::tick(vm));
                r4 = t!(vm, 1, 4, rt::load_state(inst, 1));
                t!(vm, 1, 4, rt::tick(vm));
                r5 = Value::Int(0);
                t!(vm, 1, 5, rt::tick(vm));
                r6 = Value::Int(128);
                t!(vm, 1, 6, rt::tick(vm));
                r7 = r5.clone();
                t!(vm, 1, 7, rt::tick(vm));
                r8 = r6.clone();
                pc = 8;
                continue;
            }
            8 => {
                t!(vm, 1, 8, rt::tick(vm));
                r9 = Value::bool(t!(vm, 1, 9, rt::int(&r7)) < t!(vm, 1, 9, rt::int(&r8)));
                t!(vm, 1, 9, rt::tick(vm));
                pc = if t!(vm, 1, 10, rt::int(&r9)) == 0 { 45 } else { 10 };
                continue;
            }
            10 => {
                t!(vm, 1, 10, rt::tick(vm));
                r10 = r7.clone();
                t!(vm, 1, 11, rt::tick(vm));
                r11 = t!(vm, 1, 12, rt::load_state(inst, 0));
                t!(vm, 1, 12, rt::tick(vm));
                r12 = t!(vm, 1, 13, rt::index(vm, &r11, &r10));
                t!(vm, 1, 13, rt::tick(vm));
                r13 = Value::Int(1103);
                t!(vm, 1, 14, rt::tick(vm));
                r14 = Value::Int(t!(vm, 1, 15, t!(vm, 1, 15, rt::int(&r12)).checked_mul(t!(vm, 1, 15, rt::int(&r13))).ok_or(FaultKind::Overflow)));
                t!(vm, 1, 15, rt::tick(vm));
                r15 = Value::Int(7);
                t!(vm, 1, 16, rt::tick(vm));
                r16 = Value::Int(t!(vm, 1, 17, t!(vm, 1, 17, rt::int(&r1)).checked_mul(t!(vm, 1, 17, rt::int(&r15))).ok_or(FaultKind::Overflow)));
                t!(vm, 1, 17, rt::tick(vm));
                r17 = Value::Int(t!(vm, 1, 18, t!(vm, 1, 18, rt::int(&r14)).checked_add(t!(vm, 1, 18, rt::int(&r16))).ok_or(FaultKind::Overflow)));
                t!(vm, 1, 18, rt::tick(vm));
                r18 = Value::Int(t!(vm, 1, 19, t!(vm, 1, 19, rt::int(&r17)).checked_add(t!(vm, 1, 19, rt::int(&r10))).ok_or(FaultKind::Overflow)));
                t!(vm, 1, 19, rt::tick(vm));
                r19 = Value::Int(9973);
                t!(vm, 1, 20, rt::tick(vm));
                r20 = t!(vm, 1, 21, rt::arith(ArithOp::new(Arith::Rem, Num::I64), &r18, &r19));
                t!(vm, 1, 21, rt::tick(vm));
                r21 = r10.clone();
                t!(vm, 1, 22, rt::tick(vm));
                r22 = t!(vm, 1, 23, rt::load_state(inst, 0));
                t!(vm, 1, 23, rt::tick(vm));
                { let src = r20.clone(); t!(vm, 1, 24, rt::set_path(vm, &mut r22, &[PathStep::Index(&r21)], src)); }
                t!(vm, 1, 24, rt::tick(vm));
                t!(vm, 1, 25, rt::store_state(vm, inst, 0, r22.clone()));
                t!(vm, 1, 25, rt::tick(vm));
                r23 = Value::Int(101);
                t!(vm, 1, 26, rt::tick(vm));
                r24 = t!(vm, 1, 27, rt::arith(ArithOp::new(Arith::Rem, Num::I64), &r20, &r23));
                t!(vm, 1, 27, rt::tick(vm));
                r25 = Value::Int(t!(vm, 1, 28, t!(vm, 1, 28, rt::int(&r2)).checked_add(t!(vm, 1, 28, rt::int(&r24))).ok_or(FaultKind::Overflow)));
                t!(vm, 1, 28, rt::tick(vm));
                r2 = r25.clone();
                t!(vm, 1, 29, rt::tick(vm));
                r26 = Value::Float(f64::from_bits(0x3feff7ced916872b));
                t!(vm, 1, 30, rt::tick(vm));
                r27 = Value::Float(t!(vm, 1, 31, rt::float(&r3)) * t!(vm, 1, 31, rt::float(&r26)));
                t!(vm, 1, 31, rt::tick(vm));
                r28 = t!(vm, 1, 32, rt::cast(Num::I64, Num::F64, &r20));
                t!(vm, 1, 32, rt::tick(vm));
                r29 = Value::Float(f64::from_bits(0x3f50624dd2f1a9fc));
                t!(vm, 1, 33, rt::tick(vm));
                r30 = Value::Float(t!(vm, 1, 34, rt::float(&r28)) * t!(vm, 1, 34, rt::float(&r29)));
                t!(vm, 1, 34, rt::tick(vm));
                r31 = Value::Float(t!(vm, 1, 35, rt::float(&r27)) + t!(vm, 1, 35, rt::float(&r30)));
                t!(vm, 1, 35, rt::tick(vm));
                r3 = r31.clone();
                t!(vm, 1, 36, rt::tick(vm));
                r32 = Value::Int(64);
                t!(vm, 1, 37, rt::tick(vm));
                r33 = t!(vm, 1, 38, rt::arith(ArithOp::new(Arith::Rem, Num::I64), &r20, &r32));
                t!(vm, 1, 38, rt::tick(vm));
                r34 = t!(vm, 1, 39, rt::cast(Num::I64, Num::F64, &r33));
                t!(vm, 1, 39, rt::tick(vm));
                r35 = Value::Int(t!(vm, 1, 40, t!(vm, 1, 40, rt::int(&r1)).checked_add(t!(vm, 1, 40, rt::int(&r10))).ok_or(FaultKind::Overflow)));
                t!(vm, 1, 40, rt::tick(vm));
                r36 = match t!(vm, 1, 41, rt::memo_enter(vm, inst, 0)) {
                    Some(v) => v,
                    None => { t!(vm, 1, 41, rt::depth(vm, depth)); c0(vm, inst, depth + 1, r4.clone(), r34.clone(), r35.clone())? }
                };
                t!(vm, 1, 41, rt::tick(vm));
                r4 = r36.clone();
                t!(vm, 1, 42, rt::tick(vm));
                r37 = Value::Int(1);
                t!(vm, 1, 43, rt::tick(vm));
                r7 = Value::Int(t!(vm, 1, 44, t!(vm, 1, 44, rt::int(&r7)).checked_add(t!(vm, 1, 44, rt::int(&r37))).ok_or(FaultKind::Overflow)));
                t!(vm, 1, 44, rt::tick(vm));
                pc = 8;
                continue;
            }
            45 => {
                t!(vm, 1, 45, rt::tick(vm));
                r38 = t!(vm, 1, 46, rt::load_state(inst, 3));
                t!(vm, 1, 46, rt::tick(vm));
                r39 = Value::Int(t!(vm, 1, 47, t!(vm, 1, 47, rt::int(&r38)).checked_add(t!(vm, 1, 47, rt::int(&r2))).ok_or(FaultKind::Overflow)));
                t!(vm, 1, 47, rt::tick(vm));
                r40 = Value::Int(1000003);
                t!(vm, 1, 48, rt::tick(vm));
                r41 = t!(vm, 1, 49, rt::arith(ArithOp::new(Arith::Rem, Num::I64), &r39, &r40));
                t!(vm, 1, 49, rt::tick(vm));
                t!(vm, 1, 50, rt::store_state(vm, inst, 3, r41.clone()));
                t!(vm, 1, 50, rt::tick(vm));
                t!(vm, 1, 51, rt::store_state(vm, inst, 2, r3.clone()));
                t!(vm, 1, 51, rt::tick(vm));
                t!(vm, 1, 52, rt::store_state(vm, inst, 1, r4.clone()));
                t!(vm, 1, 52, rt::tick(vm));
                r42 = Value::Int(0);
                t!(vm, 1, 53, rt::tick(vm));
                return Ok(rt::ret(vm, inst, 1, std::mem::take(&mut r42)));
            }
            _ => return Err(rt::at(vm, 1, 0, FaultKind::Internal)),
        }
    }
}

fn s1(vm: &mut Vm, inst: &mut Instance, depth: usize, args: &[Value], caps: &[Value]) -> Result<Value, FaultKind> {
    c1(vm, inst, depth, args[0].clone())
}

/// "Crowd.seeds" (chunk 2).
fn c2(vm: &mut Vm, inst: &mut Instance, depth: usize) -> Result<Value, FaultKind> {
    let mut r0 = Value::Nil;
    let mut r1 = Value::Nil;
    let mut r2 = Value::Nil;
    let mut r3 = Value::Nil;
    let mut r4 = Value::Nil;
    let mut r5 = Value::Nil;
    let mut r6 = Value::Nil;
    let mut r7 = Value::Nil;
    let mut r8 = Value::Nil;
    let mut r9 = Value::Nil;
    let mut r10 = Value::Nil;
    let mut r11 = Value::Nil;
    let mut r12 = Value::Nil;
    let mut r13 = Value::Nil;
    let mut r14 = Value::Nil;
    let mut r15 = Value::Nil;
    let mut r16 = Value::Nil;
    let mut r17 = Value::Nil;
    let mut r18 = Value::Nil;
    let mut r19 = Value::Nil;
    let mut r20 = Value::Nil;
    let mut r21 = Value::Nil;
    let mut r22 = Value::Nil;
    let mut r23 = Value::Nil;
    let mut r24 = Value::Nil;
    let mut r25 = Value::Nil;
    let mut r26 = Value::Nil;
    let mut r27 = Value::Nil;
    let mut r28 = Value::Nil;
    let mut r29 = Value::Nil;
    let mut r30 = Value::Nil;
    let mut r31 = Value::Nil;
    let mut r32 = Value::Nil;
    let mut r33 = Value::Nil;
    let mut r34 = Value::Nil;
    let mut r35 = Value::Nil;
    let mut r36 = Value::Nil;
    let mut r37 = Value::Nil;
    let mut r38 = Value::Nil;
    let mut r39 = Value::Nil;
    let mut r40 = Value::Nil;
    let mut r41 = Value::Nil;
    let mut r42 = Value::Nil;
    let mut r43 = Value::Nil;
    let mut r44 = Value::Nil;
    let mut r45 = Value::Nil;
    let mut r46 = Value::Nil;
    let mut r47 = Value::Nil;
    let mut r48 = Value::Nil;
    let mut r49 = Value::Nil;
    let mut r50 = Value::Nil;
    let mut r51 = Value::Nil;
    let mut r52 = Value::Nil;
    let mut r53 = Value::Nil;
    let mut r54 = Value::Nil;
    let mut r55 = Value::Nil;
    let mut r56 = Value::Nil;
    let mut r57 = Value::Nil;
    let mut r58 = Value::Nil;
    let mut r59 = Value::Nil;
    let mut r60 = Value::Nil;
    let mut r61 = Value::Nil;
    let mut r62 = Value::Nil;
    let mut r63 = Value::Nil;
    let mut r64 = Value::Nil;
    let mut r65 = Value::Nil;
    let mut r66 = Value::Nil;
    let mut r67 = Value::Nil;
    let mut r68 = Value::Nil;
    let mut r69 = Value::Nil;
    let mut r70 = Value::Nil;
    let mut r71 = Value::Nil;
    let mut r72 = Value::Nil;
    let mut r73 = Value::Nil;
    let mut r74 = Value::Nil;
    let mut r75 = Value::Nil;
    let mut r76 = Value::Nil;
    let mut r77 = Value::Nil;
    let mut r78 = Value::Nil;
    let mut r79 = Value::Nil;
    let mut r80 = Value::Nil;
    let mut r81 = Value::Nil;
    let mut r82 = Value::Nil;
    let mut r83 = Value::Nil;
    let mut r84 = Value::Nil;
    let mut r85 = Value::Nil;
    let mut r86 = Value::Nil;
    let mut r87 = Value::Nil;
    let mut r88 = Value::Nil;
    let mut r89 = Value::Nil;
    let mut r90 = Value::Nil;
    let mut r91 = Value::Nil;
    let mut r92 = Value::Nil;
    let mut r93 = Value::Nil;
    let mut r94 = Value::Nil;
    let mut r95 = Value::Nil;
    let mut r96 = Value::Nil;
    let mut r97 = Value::Nil;
    let mut r98 = Value::Nil;
    let mut r99 = Value::Nil;
    let mut r100 = Value::Nil;
    let mut r101 = Value::Nil;
    let mut r102 = Value::Nil;
    let mut r103 = Value::Nil;
    let mut r104 = Value::Nil;
    let mut r105 = Value::Nil;
    let mut r106 = Value::Nil;
    let mut r107 = Value::Nil;
    let mut r108 = Value::Nil;
    let mut r109 = Value::Nil;
    let mut r110 = Value::Nil;
    let mut r111 = Value::Nil;
    let mut r112 = Value::Nil;
    let mut r113 = Value::Nil;
    let mut r114 = Value::Nil;
    let mut r115 = Value::Nil;
    let mut r116 = Value::Nil;
    let mut r117 = Value::Nil;
    let mut r118 = Value::Nil;
    let mut r119 = Value::Nil;
    let mut r120 = Value::Nil;
    let mut r121 = Value::Nil;
    let mut r122 = Value::Nil;
    let mut r123 = Value::Nil;
    let mut r124 = Value::Nil;
    let mut r125 = Value::Nil;
    let mut r126 = Value::Nil;
    let mut r127 = Value::Nil;
    let mut r128 = Value::Nil;
    let mut pc: u32 = 0;
    loop {
        match pc {
            0 => {
                t!(vm, 2, 0, rt::tick(vm));
                r0 = Value::Int(7411);
                t!(vm, 2, 1, rt::tick(vm));
                r1 = Value::Int(9171);
                t!(vm, 2, 2, rt::tick(vm));
                r2 = Value::Int(7629);
                t!(vm, 2, 3, rt::tick(vm));
                r3 = Value::Int(7402);
                t!(vm, 2, 4, rt::tick(vm));
                r4 = Value::Int(8320);
                t!(vm, 2, 5, rt::tick(vm));
                r5 = Value::Int(9623);
                t!(vm, 2, 6, rt::tick(vm));
                r6 = Value::Int(3111);
                t!(vm, 2, 7, rt::tick(vm));
                r7 = Value::Int(3025);
                t!(vm, 2, 8, rt::tick(vm));
                r8 = Value::Int(8387);
                t!(vm, 2, 9, rt::tick(vm));
                r9 = Value::Int(7794);
                t!(vm, 2, 10, rt::tick(vm));
                r10 = Value::Int(3050);
                t!(vm, 2, 11, rt::tick(vm));
                r11 = Value::Int(1542);
                t!(vm, 2, 12, rt::tick(vm));
                r12 = Value::Int(7316);
                t!(vm, 2, 13, rt::tick(vm));
                r13 = Value::Int(4970);
                t!(vm, 2, 14, rt::tick(vm));
                r14 = Value::Int(2323);
                t!(vm, 2, 15, rt::tick(vm));
                r15 = Value::Int(1485);
                t!(vm, 2, 16, rt::tick(vm));
                r16 = Value::Int(8825);
                t!(vm, 2, 17, rt::tick(vm));
                r17 = Value::Int(686);
                t!(vm, 2, 18, rt::tick(vm));
                r18 = Value::Int(9755);
                t!(vm, 2, 19, rt::tick(vm));
                r19 = Value::Int(6490);
                t!(vm, 2, 20, rt::tick(vm));
                r20 = Value::Int(7421);
                t!(vm, 2, 21, rt::tick(vm));
                r21 = Value::Int(2580);
                t!(vm, 2, 22, rt::tick(vm));
                r22 = Value::Int(245);
                t!(vm, 2, 23, rt::tick(vm));
                r23 = Value::Int(8656);
                t!(vm, 2, 24, rt::tick(vm));
                r24 = Value::Int(1034);
                t!(vm, 2, 25, rt::tick(vm));
                r25 = Value::Int(975);
                t!(vm, 2, 26, rt::tick(vm));
                r26 = Value::Int(584);
                t!(vm, 2, 27, rt::tick(vm));
                r27 = Value::Int(3116);
                t!(vm, 2, 28, rt::tick(vm));
                r28 = Value::Int(3963);
                t!(vm, 2, 29, rt::tick(vm));
                r29 = Value::Int(9824);
                t!(vm, 2, 30, rt::tick(vm));
                r30 = Value::Int(492);
                t!(vm, 2, 31, rt::tick(vm));
                r31 = Value::Int(7601);
                t!(vm, 2, 32, rt::tick(vm));
                r32 = Value::Int(5345);
                t!(vm, 2, 33, rt::tick(vm));
                r33 = Value::Int(7217);
                t!(vm, 2, 34, rt::tick(vm));
                r34 = Value::Int(9682);
                t!(vm, 2, 35, rt::tick(vm));
                r35 = Value::Int(3200);
                t!(vm, 2, 36, rt::tick(vm));
                r36 = Value::Int(8505);
                t!(vm, 2, 37, rt::tick(vm));
                r37 = Value::Int(3828);
                t!(vm, 2, 38, rt::tick(vm));
                r38 = Value::Int(4819);
                t!(vm, 2, 39, rt::tick(vm));
                r39 = Value::Int(8188);
                t!(vm, 2, 40, rt::tick(vm));
                r40 = Value::Int(75);
                t!(vm, 2, 41, rt::tick(vm));
                r41 = Value::Int(1392);
                t!(vm, 2, 42, rt::tick(vm));
                r42 = Value::Int(7492);
                t!(vm, 2, 43, rt::tick(vm));
                r43 = Value::Int(4557);
                t!(vm, 2, 44, rt::tick(vm));
                r44 = Value::Int(6664);
                t!(vm, 2, 45, rt::tick(vm));
                r45 = Value::Int(9031);
                t!(vm, 2, 46, rt::tick(vm));
                r46 = Value::Int(1363);
                t!(vm, 2, 47, rt::tick(vm));
                r47 = Value::Int(4161);
                t!(vm, 2, 48, rt::tick(vm));
                r48 = Value::Int(5165);
                t!(vm, 2, 49, rt::tick(vm));
                r49 = Value::Int(3762);
                t!(vm, 2, 50, rt::tick(vm));
                r50 = Value::Int(8403);
                t!(vm, 2, 51, rt::tick(vm));
                r51 = Value::Int(4735);
                t!(vm, 2, 52, rt::tick(vm));
                r52 = Value::Int(487);
                t!(vm, 2, 53, rt::tick(vm));
                r53 = Value::Int(1150);
                t!(vm, 2, 54, rt::tick(vm));
                r54 = Value::Int(9226);
                t!(vm, 2, 55, rt::tick(vm));
                r55 = Value::Int(1768);
                t!(vm, 2, 56, rt::tick(vm));
                r56 = Value::Int(6560);
                t!(vm, 2, 57, rt::tick(vm));
                r57 = Value::Int(1766);
                t!(vm, 2, 58, rt::tick(vm));
                r58 = Value::Int(4766);
                t!(vm, 2, 59, rt::tick(vm));
                r59 = Value::Int(6332);
                t!(vm, 2, 60, rt::tick(vm));
                r60 = Value::Int(1094);
                t!(vm, 2, 61, rt::tick(vm));
                r61 = Value::Int(276);
                t!(vm, 2, 62, rt::tick(vm));
                r62 = Value::Int(8);
                t!(vm, 2, 63, rt::tick(vm));
                r63 = Value::Int(3498);
                t!(vm, 2, 64, rt::tick(vm));
                r64 = Value::Int(3436);
                t!(vm, 2, 65, rt::tick(vm));
                r65 = Value::Int(857);
                t!(vm, 2, 66, rt::tick(vm));
                r66 = Value::Int(7700);
                t!(vm, 2, 67, rt::tick(vm));
                r67 = Value::Int(6151);
                t!(vm, 2, 68, rt::tick(vm));
                r68 = Value::Int(6511);
                t!(vm, 2, 69, rt::tick(vm));
                r69 = Value::Int(6877);
                t!(vm, 2, 70, rt::tick(vm));
                r70 = Value::Int(1196);
                t!(vm, 2, 71, rt::tick(vm));
                r71 = Value::Int(9277);
                t!(vm, 2, 72, rt::tick(vm));
                r72 = Value::Int(3252);
                t!(vm, 2, 73, rt::tick(vm));
                r73 = Value::Int(4420);
                t!(vm, 2, 74, rt::tick(vm));
                r74 = Value::Int(5519);
                t!(vm, 2, 75, rt::tick(vm));
                r75 = Value::Int(1427);
                t!(vm, 2, 76, rt::tick(vm));
                r76 = Value::Int(5098);
                t!(vm, 2, 77, rt::tick(vm));
                r77 = Value::Int(5449);
                t!(vm, 2, 78, rt::tick(vm));
                r78 = Value::Int(248);
                t!(vm, 2, 79, rt::tick(vm));
                r79 = Value::Int(6718);
                t!(vm, 2, 80, rt::tick(vm));
                r80 = Value::Int(1933);
                t!(vm, 2, 81, rt::tick(vm));
                r81 = Value::Int(2205);
                t!(vm, 2, 82, rt::tick(vm));
                r82 = Value::Int(4036);
                t!(vm, 2, 83, rt::tick(vm));
                r83 = Value::Int(1655);
                t!(vm, 2, 84, rt::tick(vm));
                r84 = Value::Int(179);
                t!(vm, 2, 85, rt::tick(vm));
                r85 = Value::Int(981);
                t!(vm, 2, 86, rt::tick(vm));
                r86 = Value::Int(7617);
                t!(vm, 2, 87, rt::tick(vm));
                r87 = Value::Int(7976);
                t!(vm, 2, 88, rt::tick(vm));
                r88 = Value::Int(2911);
                t!(vm, 2, 89, rt::tick(vm));
                r89 = Value::Int(9163);
                t!(vm, 2, 90, rt::tick(vm));
                r90 = Value::Int(3086);
                t!(vm, 2, 91, rt::tick(vm));
                r91 = Value::Int(7330);
                t!(vm, 2, 92, rt::tick(vm));
                r92 = Value::Int(8337);
                t!(vm, 2, 93, rt::tick(vm));
                r93 = Value::Int(3124);
                t!(vm, 2, 94, rt::tick(vm));
                r94 = Value::Int(2145);
                t!(vm, 2, 95, rt::tick(vm));
                r95 = Value::Int(6868);
                t!(vm, 2, 96, rt::tick(vm));
                r96 = Value::Int(6287);
                t!(vm, 2, 97, rt::tick(vm));
                r97 = Value::Int(1908);
                t!(vm, 2, 98, rt::tick(vm));
                r98 = Value::Int(6469);
                t!(vm, 2, 99, rt::tick(vm));
                r99 = Value::Int(6893);
                t!(vm, 2, 100, rt::tick(vm));
                r100 = Value::Int(3487);
                t!(vm, 2, 101, rt::tick(vm));
                r101 = Value::Int(7);
                t!(vm, 2, 102, rt::tick(vm));
                r102 = Value::Int(4420);
                t!(vm, 2, 103, rt::tick(vm));
                r103 = Value::Int(9711);
                t!(vm, 2, 104, rt::tick(vm));
                r104 = Value::Int(4983);
                t!(vm, 2, 105, rt::tick(vm));
                r105 = Value::Int(321);
                t!(vm, 2, 106, rt::tick(vm));
                r106 = Value::Int(3452);
                t!(vm, 2, 107, rt::tick(vm));
                r107 = Value::Int(3068);
                t!(vm, 2, 108, rt::tick(vm));
                r108 = Value::Int(6459);
                t!(vm, 2, 109, rt::tick(vm));
                r109 = Value::Int(9863);
                t!(vm, 2, 110, rt::tick(vm));
                r110 = Value::Int(9452);
                t!(vm, 2, 111, rt::tick(vm));
                r111 = Value::Int(1643);
                t!(vm, 2, 112, rt::tick(vm));
                r112 = Value::Int(689);
                t!(vm, 2, 113, rt::tick(vm));
                r113 = Value::Int(2397);
                t!(vm, 2, 114, rt::tick(vm));
                r114 = Value::Int(3493);
                t!(vm, 2, 115, rt::tick(vm));
                r115 = Value::Int(7234);
                t!(vm, 2, 116, rt::tick(vm));
                r116 = Value::Int(4231);
                t!(vm, 2, 117, rt::tick(vm));
                r117 = Value::Int(156);
                t!(vm, 2, 118, rt::tick(vm));
                r118 = Value::Int(5389);
                t!(vm, 2, 119, rt::tick(vm));
                r119 = Value::Int(4854);
                t!(vm, 2, 120, rt::tick(vm));
                r120 = Value::Int(6327);
                t!(vm, 2, 121, rt::tick(vm));
                r121 = Value::Int(1202);
                t!(vm, 2, 122, rt::tick(vm));
                r122 = Value::Int(1217);
                t!(vm, 2, 123, rt::tick(vm));
                r123 = Value::Int(1476);
                t!(vm, 2, 124, rt::tick(vm));
                r124 = Value::Int(3419);
                t!(vm, 2, 125, rt::tick(vm));
                r125 = Value::Int(9547);
                t!(vm, 2, 126, rt::tick(vm));
                r126 = Value::Int(3981);
                t!(vm, 2, 127, rt::tick(vm));
                r127 = Value::Int(254);
                t!(vm, 2, 128, rt::tick(vm));
                r128 = t!(vm, 2, 129, rt::list(vm, vec![r0.clone(), r1.clone(), r2.clone(), r3.clone(), r4.clone(), r5.clone(), r6.clone(), r7.clone(), r8.clone(), r9.clone(), r10.clone(), r11.clone(), r12.clone(), r13.clone(), r14.clone(), r15.clone(), r16.clone(), r17.clone(), r18.clone(), r19.clone(), r20.clone(), r21.clone(), r22.clone(), r23.clone(), r24.clone(), r25.clone(), r26.clone(), r27.clone(), r28.clone(), r29.clone(), r30.clone(), r31.clone(), r32.clone(), r33.clone(), r34.clone(), r35.clone(), r36.clone(), r37.clone(), r38.clone(), r39.clone(), r40.clone(), r41.clone(), r42.clone(), r43.clone(), r44.clone(), r45.clone(), r46.clone(), r47.clone(), r48.clone(), r49.clone(), r50.clone(), r51.clone(), r52.clone(), r53.clone(), r54.clone(), r55.clone(), r56.clone(), r57.clone(), r58.clone(), r59.clone(), r60.clone(), r61.clone(), r62.clone(), r63.clone(), r64.clone(), r65.clone(), r66.clone(), r67.clone(), r68.clone(), r69.clone(), r70.clone(), r71.clone(), r72.clone(), r73.clone(), r74.clone(), r75.clone(), r76.clone(), r77.clone(), r78.clone(), r79.clone(), r80.clone(), r81.clone(), r82.clone(), r83.clone(), r84.clone(), r85.clone(), r86.clone(), r87.clone(), r88.clone(), r89.clone(), r90.clone(), r91.clone(), r92.clone(), r93.clone(), r94.clone(), r95.clone(), r96.clone(), r97.clone(), r98.clone(), r99.clone(), r100.clone(), r101.clone(), r102.clone(), r103.clone(), r104.clone(), r105.clone(), r106.clone(), r107.clone(), r108.clone(), r109.clone(), r110.clone(), r111.clone(), r112.clone(), r113.clone(), r114.clone(), r115.clone(), r116.clone(), r117.clone(), r118.clone(), r119.clone(), r120.clone(), r121.clone(), r122.clone(), r123.clone(), r124.clone(), r125.clone(), r126.clone(), r127.clone()]));
                t!(vm, 2, 129, rt::tick(vm));
                return Ok(rt::ret(vm, inst, 2, std::mem::take(&mut r128)));
            }
            _ => return Err(rt::at(vm, 2, 0, FaultKind::Internal)),
        }
    }
}

fn s2(vm: &mut Vm, inst: &mut Instance, depth: usize, args: &[Value], caps: &[Value]) -> Result<Value, FaultKind> {
    c2(vm, inst, depth)
}

/// "Crowd.lead" (chunk 3).
fn c3(vm: &mut Vm, inst: &mut Instance, depth: usize) -> Result<Value, FaultKind> {
    let mut r0 = Value::Nil;
    let mut r1 = Value::Nil;
    let mut r2 = Value::Nil;
    let mut r3 = Value::Nil;
    let mut pc: u32 = 0;
    loop {
        match pc {
            0 => {
                t!(vm, 3, 0, rt::tick(vm));
                r0 = Value::Float(f64::from_bits(0x0));
                t!(vm, 3, 1, rt::tick(vm));
                r1 = Value::Float(f64::from_bits(0x0));
                t!(vm, 3, 2, rt::tick(vm));
                r2 = Value::Int(3);
                t!(vm, 3, 3, rt::tick(vm));
                r3 = t!(vm, 3, 4, rt::make(vm, 0, Box::from([r0.clone(), r1.clone(), r2.clone()])));
                t!(vm, 3, 4, rt::tick(vm));
                return Ok(rt::ret(vm, inst, 3, std::mem::take(&mut r3)));
            }
            _ => return Err(rt::at(vm, 3, 0, FaultKind::Internal)),
        }
    }
}

fn s3(vm: &mut Vm, inst: &mut Instance, depth: usize, args: &[Value], caps: &[Value]) -> Result<Value, FaultKind> {
    c3(vm, inst, depth)
}

/// "Crowd.energy" (chunk 4).
fn c4(vm: &mut Vm, inst: &mut Instance, depth: usize) -> Result<Value, FaultKind> {
    let mut r0 = Value::Nil;
    let mut pc: u32 = 0;
    loop {
        match pc {
            0 => {
                t!(vm, 4, 0, rt::tick(vm));
                r0 = Value::Float(f64::from_bits(0x0));
                t!(vm, 4, 1, rt::tick(vm));
                return Ok(rt::ret(vm, inst, 4, std::mem::take(&mut r0)));
            }
            _ => return Err(rt::at(vm, 4, 0, FaultKind::Internal)),
        }
    }
}

fn s4(vm: &mut Vm, inst: &mut Instance, depth: usize, args: &[Value], caps: &[Value]) -> Result<Value, FaultKind> {
    c4(vm, inst, depth)
}

/// "Crowd.checksum" (chunk 5).
fn c5(vm: &mut Vm, inst: &mut Instance, depth: usize) -> Result<Value, FaultKind> {
    let mut r0 = Value::Nil;
    let mut pc: u32 = 0;
    loop {
        match pc {
            0 => {
                t!(vm, 5, 0, rt::tick(vm));
                r0 = Value::Int(0);
                t!(vm, 5, 1, rt::tick(vm));
                return Ok(rt::ret(vm, inst, 5, std::mem::take(&mut r0)));
            }
            _ => return Err(rt::at(vm, 5, 0, FaultKind::Internal)),
        }
    }
}

fn s5(vm: &mut Vm, inst: &mut Instance, depth: usize, args: &[Value], caps: &[Value]) -> Result<Value, FaultKind> {
    c5(vm, inst, depth)
}
